/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.routines;


import com.rodiejacontable.database.jooq.SistemaVehicular;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListarComisionesPendientes extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>sistema_vehicular.listar_comisiones_pendientes.p_anio</code>.
     */
    public static final Parameter<Integer> P_ANIO = Internal.createParameter("p_anio", SQLDataType.INTEGER, false, false);

    /**
     * The parameter
     * <code>sistema_vehicular.listar_comisiones_pendientes.p_mes</code>.
     */
    public static final Parameter<Integer> P_MES = Internal.createParameter("p_mes", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public ListarComisionesPendientes() {
        super("listar_comisiones_pendientes", SistemaVehicular.SISTEMA_VEHICULAR);

        addInParameter(P_ANIO);
        addInParameter(P_MES);
    }

    /**
     * Set the <code>p_anio</code> parameter IN value to the routine
     */
    public void setPAnio(Integer value) {
        setValue(P_ANIO, value);
    }

    /**
     * Set the <code>p_mes</code> parameter IN value to the routine
     */
    public void setPMes(Integer value) {
        setValue(P_MES, value);
    }
}
