/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.routines;


import com.rodiejacontable.database.jooq.SistemaVehicular;

import java.time.LocalDate;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpActividadAuditoriaFecha extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>sistema_vehicular.sp_actividad_auditoria_fecha.p_fecha_inicio</code>.
     */
    public static final Parameter<LocalDate> P_FECHA_INICIO = Internal.createParameter("p_fecha_inicio", SQLDataType.LOCALDATE, false, false);

    /**
     * The parameter
     * <code>sistema_vehicular.sp_actividad_auditoria_fecha.p_fecha_fin</code>.
     */
    public static final Parameter<LocalDate> P_FECHA_FIN = Internal.createParameter("p_fecha_fin", SQLDataType.LOCALDATE, false, false);

    /**
     * Create a new routine call instance
     */
    public SpActividadAuditoriaFecha() {
        super("sp_actividad_auditoria_fecha", SistemaVehicular.SISTEMA_VEHICULAR);

        addInParameter(P_FECHA_INICIO);
        addInParameter(P_FECHA_FIN);
    }

    /**
     * Set the <code>p_fecha_inicio</code> parameter IN value to the routine
     */
    public void setPFechaInicio(LocalDate value) {
        setValue(P_FECHA_INICIO, value);
    }

    /**
     * Set the <code>p_fecha_fin</code> parameter IN value to the routine
     */
    public void setPFechaFin(LocalDate value) {
        setValue(P_FECHA_FIN, value);
    }
}
