/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables;


import com.rodiejacontable.database.jooq.Indexes;
import com.rodiejacontable.database.jooq.Keys;
import com.rodiejacontable.database.jooq.SistemaVehicular;
import com.rodiejacontable.database.jooq.tables.records.AudatexPedidoItemsRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AudatexPedidoItems extends TableImpl<AudatexPedidoItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>sistema_vehicular.audatex_pedido_items</code>
     */
    public static final AudatexPedidoItems AUDATEX_PEDIDO_ITEMS = new AudatexPedidoItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AudatexPedidoItemsRecord> getRecordType() {
        return AudatexPedidoItemsRecord.class;
    }

    /**
     * The column <code>sistema_vehicular.audatex_pedido_items.id</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sistema_vehicular.audatex_pedido_items.pedido_id</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, Integer> PEDIDO_ID = createField(DSL.name("pedido_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.audatex_pedido_items.repuesto_id</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, Integer> REPUESTO_ID = createField(DSL.name("repuesto_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.audatex_pedido_items.precio_ofrecido</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, BigDecimal> PRECIO_OFRECIDO = createField(DSL.name("precio_ofrecido"), SQLDataType.DECIMAL(12, 2).nullable(false), this, "");

    /**
     * The column <code>sistema_vehicular.audatex_pedido_items.cantidad</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, Integer> CANTIDAD = createField(DSL.name("cantidad"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.audatex_pedido_items.descripcion</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, String> DESCRIPCION = createField(DSL.name("descripcion"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.audatex_pedido_items.tipo_pieza</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, String> TIPO_PIEZA = createField(DSL.name("tipo_pieza"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.audatex_pedido_items.dias_entrega</code>.
     */
    public final TableField<AudatexPedidoItemsRecord, Integer> DIAS_ENTREGA = createField(DSL.name("dias_entrega"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private AudatexPedidoItems(Name alias, Table<AudatexPedidoItemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AudatexPedidoItems(Name alias, Table<AudatexPedidoItemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>sistema_vehicular.audatex_pedido_items</code>
     * table reference
     */
    public AudatexPedidoItems(String alias) {
        this(DSL.name(alias), AUDATEX_PEDIDO_ITEMS);
    }

    /**
     * Create an aliased <code>sistema_vehicular.audatex_pedido_items</code>
     * table reference
     */
    public AudatexPedidoItems(Name alias) {
        this(alias, AUDATEX_PEDIDO_ITEMS);
    }

    /**
     * Create a <code>sistema_vehicular.audatex_pedido_items</code> table
     * reference
     */
    public AudatexPedidoItems() {
        this(DSL.name("audatex_pedido_items"), null);
    }

    public <O extends Record> AudatexPedidoItems(Table<O> child, ForeignKey<O, AudatexPedidoItemsRecord> key) {
        super(child, key, AUDATEX_PEDIDO_ITEMS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SistemaVehicular.SISTEMA_VEHICULAR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDATEX_PEDIDO_ITEMS_PEDIDO_ID);
    }

    @Override
    public Identity<AudatexPedidoItemsRecord, Integer> getIdentity() {
        return (Identity<AudatexPedidoItemsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AudatexPedidoItemsRecord> getPrimaryKey() {
        return Keys.KEY_AUDATEX_PEDIDO_ITEMS_PRIMARY;
    }

    @Override
    public List<ForeignKey<AudatexPedidoItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUDATEX_PEDIDO_ITEMS_IBFK_1);
    }

    private transient AudatexPedidos _audatexPedidos;

    /**
     * Get the implicit join path to the
     * <code>sistema_vehicular.audatex_pedidos</code> table.
     */
    public AudatexPedidos audatexPedidos() {
        if (_audatexPedidos == null)
            _audatexPedidos = new AudatexPedidos(this, Keys.AUDATEX_PEDIDO_ITEMS_IBFK_1);

        return _audatexPedidos;
    }

    @Override
    public AudatexPedidoItems as(String alias) {
        return new AudatexPedidoItems(DSL.name(alias), this);
    }

    @Override
    public AudatexPedidoItems as(Name alias) {
        return new AudatexPedidoItems(alias, this);
    }

    @Override
    public AudatexPedidoItems as(Table<?> alias) {
        return new AudatexPedidoItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AudatexPedidoItems rename(String name) {
        return new AudatexPedidoItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AudatexPedidoItems rename(Name name) {
        return new AudatexPedidoItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AudatexPedidoItems rename(Table<?> name) {
        return new AudatexPedidoItems(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, Integer, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Integer, ? super Integer, ? super Integer, ? super BigDecimal, ? super Integer, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Integer, ? super Integer, ? super Integer, ? super BigDecimal, ? super Integer, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
