/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables;


import com.rodiejacontable.database.jooq.Keys;
import com.rodiejacontable.database.jooq.SistemaVehicular;
import com.rodiejacontable.database.jooq.tables.records.UserProfilepictureRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfilepicture extends TableImpl<UserProfilepictureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>sistema_vehicular.user_profilePicture</code>
     */
    public static final UserProfilepicture USER_PROFILEPICTURE = new UserProfilepicture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserProfilepictureRecord> getRecordType() {
        return UserProfilepictureRecord.class;
    }

    /**
     * The column <code>sistema_vehicular.user_profilePicture.user_id</code>.
     */
    public final TableField<UserProfilepictureRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.user_profilePicture.profile_picture</code>.
     */
    public final TableField<UserProfilepictureRecord, byte[]> PROFILE_PICTURE = createField(DSL.name("profile_picture"), SQLDataType.BLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BLOB)), this, "");

    private UserProfilepicture(Name alias, Table<UserProfilepictureRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserProfilepicture(Name alias, Table<UserProfilepictureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>sistema_vehicular.user_profilePicture</code>
     * table reference
     */
    public UserProfilepicture(String alias) {
        this(DSL.name(alias), USER_PROFILEPICTURE);
    }

    /**
     * Create an aliased <code>sistema_vehicular.user_profilePicture</code>
     * table reference
     */
    public UserProfilepicture(Name alias) {
        this(alias, USER_PROFILEPICTURE);
    }

    /**
     * Create a <code>sistema_vehicular.user_profilePicture</code> table
     * reference
     */
    public UserProfilepicture() {
        this(DSL.name("user_profilePicture"), null);
    }

    public <O extends Record> UserProfilepicture(Table<O> child, ForeignKey<O, UserProfilepictureRecord> key) {
        super(child, key, USER_PROFILEPICTURE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SistemaVehicular.SISTEMA_VEHICULAR;
    }

    @Override
    public UniqueKey<UserProfilepictureRecord> getPrimaryKey() {
        return Keys.KEY_USER_PROFILEPICTURE_PRIMARY;
    }

    @Override
    public List<ForeignKey<UserProfilepictureRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_PROFILEPICTURE_IBFK_1);
    }

    private transient Users _users;

    /**
     * Get the implicit join path to the <code>sistema_vehicular.users</code>
     * table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.USER_PROFILEPICTURE_IBFK_1);

        return _users;
    }

    @Override
    public UserProfilepicture as(String alias) {
        return new UserProfilepicture(DSL.name(alias), this);
    }

    @Override
    public UserProfilepicture as(Name alias) {
        return new UserProfilepicture(alias, this);
    }

    @Override
    public UserProfilepicture as(Table<?> alias) {
        return new UserProfilepicture(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfilepicture rename(String name) {
        return new UserProfilepicture(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfilepicture rename(Name name) {
        return new UserProfilepicture(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfilepicture rename(Table<?> name) {
        return new UserProfilepicture(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super byte[], ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super byte[], ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
