/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum InventarioRepuestosNivel implements EnumType {

    _0_("0-"),

    N1_("N1-"),

    N2_("N2-"),

    N3_("N3-"),

    N4_("N4-"),

    N5_("N5-"),

    N6_("N6-"),

    N7_("N7-"),

    N8_("N8-"),

    N9_("N9-"),

    N10_("N10-"),

    N11_("N11-"),

    N12_("N12-"),

    N13_("N13-"),

    N14_("N14-"),

    N15_("N15-"),

    N16_("N16-"),

    N17_("N17-"),

    N18_("N18-"),

    N19_("N19-"),

    N20_("N20-"),

    N21_("N21-"),

    N22_("N22-");

    private final String literal;

    private InventarioRepuestosNivel(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static InventarioRepuestosNivel lookupLiteral(String literal) {
        return EnumType.lookupLiteral(InventarioRepuestosNivel.class, literal);
    }
}
