/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum InventarioRepuestosHorizontal implements EnumType {

    _0_("0-"),

    HA_("HA-"),

    HB_("HB-"),

    HC_("HC-"),

    HD_("HD-"),

    HE_("HE-"),

    HF_("HF-"),

    HG_("HG-"),

    HH_("HH-"),

    HI_("HI-"),

    HJ_("HJ-"),

    HK_("HK-"),

    HL_("HL-"),

    HM_("HM-"),

    HN_("HN-"),

    HO_("HO-"),

    HP_("HP-"),

    HQ_("HQ-"),

    HR_("HR-"),

    HS_("HS-"),

    HT_("HT-");

    private final String literal;

    private InventarioRepuestosHorizontal(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static InventarioRepuestosHorizontal lookupLiteral(String literal) {
        return EnumType.lookupLiteral(InventarioRepuestosHorizontal.class, literal);
    }
}
