/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum InventarioRepuestosPiso implements EnumType {

    P1_("P1-"),

    P2_("P2-"),

    P3_("P3-"),

    P4_("P4-"),

    P5_("P5-"),

    P6_("P6-"),

    P7_("P7-"),

    P8_("P8-"),

    P9_("P9-"),

    P10_("P10-"),

    P11_("P11-"),

    P12_("P12-"),

    P13_("P13-"),

    P14_("P14-"),

    P15_("P15-"),

    P16_("P16-"),

    P17_("P17-"),

    P18_("P18-"),

    P19_("P19-"),

    P20_("P20-"),

    P21_("P21-");

    private final String literal;

    private InventarioRepuestosPiso(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static InventarioRepuestosPiso lookupLiteral(String literal) {
        return EnumType.lookupLiteral(InventarioRepuestosPiso.class, literal);
    }
}
