/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum InventarioRepuestosCarton implements EnumType {

    MM1_("MM1-"),

    MM2_("MM2-"),

    MM3_("MM3-"),

    MM4_("MM4-"),

    MM5_("MM5-"),

    MM6_("MM6-"),

    MM7_("MM7-"),

    MM8_("MM8-"),

    MM9_("MM9-"),

    MM10_("MM10-"),

    MM11_("MM11-"),

    MM12_("MM12-"),

    MM13_("MM13-"),

    MM14_("MM14-"),

    MM15_("MM15-"),

    MM16_("MM16-"),

    MM17_("MM17-"),

    MM18_("MM18-"),

    MM19_("MM19-"),

    MM20_("MM20-"),

    MM21_("MM21-"),

    MM22_("MM22-"),

    MM23_("MM23-"),

    MM24_("MM24-"),

    MM25_("MM25-"),

    MM26_("MM26-"),

    MM27_("MM27-"),

    MM28_("MM28-"),

    MM29_("MM29-"),

    MM30_("MM30-"),

    MM31_("MM31-"),

    MM32_("MM32-"),

    MM33_("MM33-"),

    MM34_("MM34-"),

    MM35_("MM35-"),

    MM36_("MM36-"),

    MM37_("MM37-"),

    MM38_("MM38-"),

    MM39_("MM39-"),

    MM40_("MM40-"),

    MM41_("MM41-"),

    MM42_("MM42-"),

    MM43_("MM43-"),

    MM44_("MM44-"),

    MM45_("MM45-"),

    MM46_("MM46-"),

    MM47_("MM47-"),

    MM48_("MM48-"),

    MM49_("MM49-"),

    MM50_("MM50-"),

    MM51_("MM51-"),

    MM52_("MM52-");

    private final String literal;

    private InventarioRepuestosCarton(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static InventarioRepuestosCarton lookupLiteral(String literal) {
        return EnumType.lookupLiteral(InventarioRepuestosCarton.class, literal);
    }
}
