/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum VehiculosTraccion implements EnumType {

    _4x2("4x2"),

    _4x4("4x4");

    private final String literal;

    private VehiculosTraccion(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static VehiculosTraccion lookupLiteral(String literal) {
        return EnumType.lookupLiteral(VehiculosTraccion.class, literal);
    }
}
