/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum VistaTransaccionesCompletasCategoria implements EnumType {

    INGRESO("INGRESO"),

    EGRESO("EGRESO");

    private final String literal;

    private VistaTransaccionesCompletasCategoria(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static VistaTransaccionesCompletasCategoria lookupLiteral(String literal) {
        return EnumType.lookupLiteral(VistaTransaccionesCompletasCategoria.class, literal);
    }
}
