/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.HistorialVehiculosAccion;
import com.rodiejacontable.database.jooq.tables.HistorialVehiculos;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistorialVehiculosRecord extends UpdatableRecordImpl<HistorialVehiculosRecord> implements Record10<Integer, Integer, HistorialVehiculosAccion, String, String, String, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.id</code>.
     */
    public HistorialVehiculosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.vehiculo_id</code>.
     */
    public HistorialVehiculosRecord setVehiculoId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.vehiculo_id</code>.
     */
    public Integer getVehiculoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.accion</code>.
     */
    public HistorialVehiculosRecord setAccion(HistorialVehiculosAccion value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.accion</code>.
     */
    public HistorialVehiculosAccion getAccion() {
        return (HistorialVehiculosAccion) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.campo_modificado</code>.
     */
    public HistorialVehiculosRecord setCampoModificado(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.campo_modificado</code>.
     */
    public String getCampoModificado() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.valor_anterior</code>.
     */
    public HistorialVehiculosRecord setValorAnterior(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.valor_anterior</code>.
     */
    public String getValorAnterior() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.valor_nuevo</code>.
     */
    public HistorialVehiculosRecord setValorNuevo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.valor_nuevo</code>.
     */
    public String getValorNuevo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.usuario</code>.
     */
    public HistorialVehiculosRecord setUsuario(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.usuario</code>.
     */
    public String getUsuario() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.fecha_cambio</code>.
     */
    public HistorialVehiculosRecord setFechaCambio(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.fecha_cambio</code>.
     */
    public LocalDateTime getFechaCambio() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.ip_usuario</code>.
     */
    public HistorialVehiculosRecord setIpUsuario(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.ip_usuario</code>.
     */
    public String getIpUsuario() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.observaciones</code>.
     */
    public HistorialVehiculosRecord setObservaciones(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.observaciones</code>.
     */
    public String getObservaciones() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, HistorialVehiculosAccion, String, String, String, String, LocalDateTime, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, HistorialVehiculosAccion, String, String, String, String, LocalDateTime, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.VEHICULO_ID;
    }

    @Override
    public Field<HistorialVehiculosAccion> field3() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.ACCION;
    }

    @Override
    public Field<String> field4() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.CAMPO_MODIFICADO;
    }

    @Override
    public Field<String> field5() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.VALOR_ANTERIOR;
    }

    @Override
    public Field<String> field6() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.VALOR_NUEVO;
    }

    @Override
    public Field<String> field7() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.USUARIO;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.FECHA_CAMBIO;
    }

    @Override
    public Field<String> field9() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.IP_USUARIO;
    }

    @Override
    public Field<String> field10() {
        return HistorialVehiculos.HISTORIAL_VEHICULOS.OBSERVACIONES;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getVehiculoId();
    }

    @Override
    public HistorialVehiculosAccion component3() {
        return getAccion();
    }

    @Override
    public String component4() {
        return getCampoModificado();
    }

    @Override
    public String component5() {
        return getValorAnterior();
    }

    @Override
    public String component6() {
        return getValorNuevo();
    }

    @Override
    public String component7() {
        return getUsuario();
    }

    @Override
    public LocalDateTime component8() {
        return getFechaCambio();
    }

    @Override
    public String component9() {
        return getIpUsuario();
    }

    @Override
    public String component10() {
        return getObservaciones();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getVehiculoId();
    }

    @Override
    public HistorialVehiculosAccion value3() {
        return getAccion();
    }

    @Override
    public String value4() {
        return getCampoModificado();
    }

    @Override
    public String value5() {
        return getValorAnterior();
    }

    @Override
    public String value6() {
        return getValorNuevo();
    }

    @Override
    public String value7() {
        return getUsuario();
    }

    @Override
    public LocalDateTime value8() {
        return getFechaCambio();
    }

    @Override
    public String value9() {
        return getIpUsuario();
    }

    @Override
    public String value10() {
        return getObservaciones();
    }

    @Override
    public HistorialVehiculosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value2(Integer value) {
        setVehiculoId(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value3(HistorialVehiculosAccion value) {
        setAccion(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value4(String value) {
        setCampoModificado(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value5(String value) {
        setValorAnterior(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value6(String value) {
        setValorNuevo(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value7(String value) {
        setUsuario(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value8(LocalDateTime value) {
        setFechaCambio(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value9(String value) {
        setIpUsuario(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord value10(String value) {
        setObservaciones(value);
        return this;
    }

    @Override
    public HistorialVehiculosRecord values(Integer value1, Integer value2, HistorialVehiculosAccion value3, String value4, String value5, String value6, String value7, LocalDateTime value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistorialVehiculosRecord
     */
    public HistorialVehiculosRecord() {
        super(HistorialVehiculos.HISTORIAL_VEHICULOS);
    }

    /**
     * Create a detached, initialised HistorialVehiculosRecord
     */
    public HistorialVehiculosRecord(Integer id, Integer vehiculoId, HistorialVehiculosAccion accion, String campoModificado, String valorAnterior, String valorNuevo, String usuario, LocalDateTime fechaCambio, String ipUsuario, String observaciones) {
        super(HistorialVehiculos.HISTORIAL_VEHICULOS);

        setId(id);
        setVehiculoId(vehiculoId);
        setAccion(accion);
        setCampoModificado(campoModificado);
        setValorAnterior(valorAnterior);
        setValorNuevo(valorNuevo);
        setUsuario(usuario);
        setFechaCambio(fechaCambio);
        setIpUsuario(ipUsuario);
        setObservaciones(observaciones);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised HistorialVehiculosRecord
     */
    public HistorialVehiculosRecord(com.rodiejacontable.database.jooq.tables.pojos.HistorialVehiculos value) {
        super(HistorialVehiculos.HISTORIAL_VEHICULOS);

        if (value != null) {
            setId(value.getId());
            setVehiculoId(value.getVehiculoId());
            setAccion(value.getAccion());
            setCampoModificado(value.getCampoModificado());
            setValorAnterior(value.getValorAnterior());
            setValorNuevo(value.getValorNuevo());
            setUsuario(value.getUsuario());
            setFechaCambio(value.getFechaCambio());
            setIpUsuario(value.getIpUsuario());
            setObservaciones(value.getObservaciones());
            resetChangedOnNotNull();
        }
    }
}
