/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.InventarioRepuestosBodega;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosCarton;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosCondicion;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosEstado;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosEstante;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosHorizontal;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosMalla;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosNivel;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosPared;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosParteVehiculo;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosPiso;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosPlastica;
import com.rodiejacontable.database.jooq.enums.InventarioRepuestosZona;
import com.rodiejacontable.database.jooq.tables.InventarioRepuestos;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventarioRepuestosRecord extends UpdatableRecordImpl<InventarioRepuestosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.id</code>.
     */
    public InventarioRepuestosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.codigo_repuesto</code>.
     */
    public InventarioRepuestosRecord setCodigoRepuesto(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.codigo_repuesto</code>.
     */
    public String getCodigoRepuesto() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.vehiculo_origen_id</code>.
     */
    public InventarioRepuestosRecord setVehiculoOrigenId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.vehiculo_origen_id</code>.
     */
    public Integer getVehiculoOrigenId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.anio_registro</code>.
     */
    public InventarioRepuestosRecord setAnioRegistro(Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.anio_registro</code>.
     */
    public Short getAnioRegistro() {
        return (Short) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.mes_registro</code>.
     */
    public InventarioRepuestosRecord setMesRegistro(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.mes_registro</code>.
     */
    public Byte getMesRegistro() {
        return (Byte) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.codigo_ubicacion</code>.
     */
    public InventarioRepuestosRecord setCodigoUbicacion(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.codigo_ubicacion</code>.
     */
    public String getCodigoUbicacion() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.imagen_url</code>.
     */
    public InventarioRepuestosRecord setImagenUrl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.imagen_url</code>.
     */
    public String getImagenUrl() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.parte_vehiculo</code>.
     */
    public InventarioRepuestosRecord setParteVehiculo(InventarioRepuestosParteVehiculo value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.parte_vehiculo</code>.
     */
    public InventarioRepuestosParteVehiculo getParteVehiculo() {
        return (InventarioRepuestosParteVehiculo) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.descripcion</code>.
     */
    public InventarioRepuestosRecord setDescripcion(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.precio_costo</code>.
     */
    public InventarioRepuestosRecord setPrecioCosto(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.precio_costo</code>.
     */
    public BigDecimal getPrecioCosto() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.precio_venta</code>.
     */
    public InventarioRepuestosRecord setPrecioVenta(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.precio_mayoreo</code>.
     */
    public InventarioRepuestosRecord setPrecioMayoreo(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.precio_mayoreo</code>.
     */
    public BigDecimal getPrecioMayoreo() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.formula_15</code>.
     */
    public InventarioRepuestosRecord setFormula_15(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.formula_15</code>.
     */
    public BigDecimal getFormula_15() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.formula_30</code>.
     */
    public InventarioRepuestosRecord setFormula_30(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.formula_30</code>.
     */
    public BigDecimal getFormula_30() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.bodega</code>.
     */
    public InventarioRepuestosRecord setBodega(InventarioRepuestosBodega value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.bodega</code>.
     */
    public InventarioRepuestosBodega getBodega() {
        return (InventarioRepuestosBodega) get(14);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.zona</code>.
     */
    public InventarioRepuestosRecord setZona(InventarioRepuestosZona value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.zona</code>.
     */
    public InventarioRepuestosZona getZona() {
        return (InventarioRepuestosZona) get(15);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.pared</code>.
     */
    public InventarioRepuestosRecord setPared(InventarioRepuestosPared value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.pared</code>.
     */
    public InventarioRepuestosPared getPared() {
        return (InventarioRepuestosPared) get(16);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.malla</code>.
     */
    public InventarioRepuestosRecord setMalla(InventarioRepuestosMalla value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.malla</code>.
     */
    public InventarioRepuestosMalla getMalla() {
        return (InventarioRepuestosMalla) get(17);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.horizontal</code>.
     */
    public InventarioRepuestosRecord setHorizontal(InventarioRepuestosHorizontal value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.horizontal</code>.
     */
    public InventarioRepuestosHorizontal getHorizontal() {
        return (InventarioRepuestosHorizontal) get(18);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.estante</code>.
     */
    public InventarioRepuestosRecord setEstante(InventarioRepuestosEstante value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.estante</code>.
     */
    public InventarioRepuestosEstante getEstante() {
        return (InventarioRepuestosEstante) get(19);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.nivel</code>.
     */
    public InventarioRepuestosRecord setNivel(InventarioRepuestosNivel value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.nivel</code>.
     */
    public InventarioRepuestosNivel getNivel() {
        return (InventarioRepuestosNivel) get(20);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.piso</code>.
     */
    public InventarioRepuestosRecord setPiso(InventarioRepuestosPiso value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.piso</code>.
     */
    public InventarioRepuestosPiso getPiso() {
        return (InventarioRepuestosPiso) get(21);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.plastica</code>.
     */
    public InventarioRepuestosRecord setPlastica(InventarioRepuestosPlastica value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.plastica</code>.
     */
    public InventarioRepuestosPlastica getPlastica() {
        return (InventarioRepuestosPlastica) get(22);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.carton</code>.
     */
    public InventarioRepuestosRecord setCarton(InventarioRepuestosCarton value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.carton</code>.
     */
    public InventarioRepuestosCarton getCarton() {
        return (InventarioRepuestosCarton) get(23);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.posicion</code>.
     */
    public InventarioRepuestosRecord setPosicion(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.posicion</code>.
     */
    public String getPosicion() {
        return (String) get(24);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.cantidad</code>.
     */
    public InventarioRepuestosRecord setCantidad(UInteger value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.cantidad</code>.
     */
    public UInteger getCantidad() {
        return (UInteger) get(25);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.estado</code>.
     */
    public InventarioRepuestosRecord setEstado(InventarioRepuestosEstado value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.estado</code>.
     */
    public InventarioRepuestosEstado getEstado() {
        return (InventarioRepuestosEstado) get(26);
    }

    /**
     * Setter for <code>sistema_vehicular.inventario_repuestos.condicion</code>.
     */
    public InventarioRepuestosRecord setCondicion(InventarioRepuestosCondicion value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.inventario_repuestos.condicion</code>.
     */
    public InventarioRepuestosCondicion getCondicion() {
        return (InventarioRepuestosCondicion) get(27);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.fecha_creacion</code>.
     */
    public InventarioRepuestosRecord setFechaCreacion(LocalDateTime value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(28);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.inventario_repuestos.fecha_actualizacion</code>.
     */
    public InventarioRepuestosRecord setFechaActualizacion(LocalDateTime value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.inventario_repuestos.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return (LocalDateTime) get(29);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventarioRepuestosRecord
     */
    public InventarioRepuestosRecord() {
        super(InventarioRepuestos.INVENTARIO_REPUESTOS);
    }

    /**
     * Create a detached, initialised InventarioRepuestosRecord
     */
    public InventarioRepuestosRecord(Integer id, String codigoRepuesto, Integer vehiculoOrigenId, Short anioRegistro, Byte mesRegistro, String codigoUbicacion, String imagenUrl, InventarioRepuestosParteVehiculo parteVehiculo, String descripcion, BigDecimal precioCosto, BigDecimal precioVenta, BigDecimal precioMayoreo, BigDecimal formula_15, BigDecimal formula_30, InventarioRepuestosBodega bodega, InventarioRepuestosZona zona, InventarioRepuestosPared pared, InventarioRepuestosMalla malla, InventarioRepuestosHorizontal horizontal, InventarioRepuestosEstante estante, InventarioRepuestosNivel nivel, InventarioRepuestosPiso piso, InventarioRepuestosPlastica plastica, InventarioRepuestosCarton carton, String posicion, UInteger cantidad, InventarioRepuestosEstado estado, InventarioRepuestosCondicion condicion, LocalDateTime fechaCreacion, LocalDateTime fechaActualizacion) {
        super(InventarioRepuestos.INVENTARIO_REPUESTOS);

        setId(id);
        setCodigoRepuesto(codigoRepuesto);
        setVehiculoOrigenId(vehiculoOrigenId);
        setAnioRegistro(anioRegistro);
        setMesRegistro(mesRegistro);
        setCodigoUbicacion(codigoUbicacion);
        setImagenUrl(imagenUrl);
        setParteVehiculo(parteVehiculo);
        setDescripcion(descripcion);
        setPrecioCosto(precioCosto);
        setPrecioVenta(precioVenta);
        setPrecioMayoreo(precioMayoreo);
        setFormula_15(formula_15);
        setFormula_30(formula_30);
        setBodega(bodega);
        setZona(zona);
        setPared(pared);
        setMalla(malla);
        setHorizontal(horizontal);
        setEstante(estante);
        setNivel(nivel);
        setPiso(piso);
        setPlastica(plastica);
        setCarton(carton);
        setPosicion(posicion);
        setCantidad(cantidad);
        setEstado(estado);
        setCondicion(condicion);
        setFechaCreacion(fechaCreacion);
        setFechaActualizacion(fechaActualizacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised InventarioRepuestosRecord
     */
    public InventarioRepuestosRecord(com.rodiejacontable.database.jooq.tables.pojos.InventarioRepuestos value) {
        super(InventarioRepuestos.INVENTARIO_REPUESTOS);

        if (value != null) {
            setId(value.getId());
            setCodigoRepuesto(value.getCodigoRepuesto());
            setVehiculoOrigenId(value.getVehiculoOrigenId());
            setAnioRegistro(value.getAnioRegistro());
            setMesRegistro(value.getMesRegistro());
            setCodigoUbicacion(value.getCodigoUbicacion());
            setImagenUrl(value.getImagenUrl());
            setParteVehiculo(value.getParteVehiculo());
            setDescripcion(value.getDescripcion());
            setPrecioCosto(value.getPrecioCosto());
            setPrecioVenta(value.getPrecioVenta());
            setPrecioMayoreo(value.getPrecioMayoreo());
            setFormula_15(value.getFormula_15());
            setFormula_30(value.getFormula_30());
            setBodega(value.getBodega());
            setZona(value.getZona());
            setPared(value.getPared());
            setMalla(value.getMalla());
            setHorizontal(value.getHorizontal());
            setEstante(value.getEstante());
            setNivel(value.getNivel());
            setPiso(value.getPiso());
            setPlastica(value.getPlastica());
            setCarton(value.getCarton());
            setPosicion(value.getPosicion());
            setCantidad(value.getCantidad());
            setEstado(value.getEstado());
            setCondicion(value.getCondicion());
            setFechaCreacion(value.getFechaCreacion());
            setFechaActualizacion(value.getFechaActualizacion());
            resetChangedOnNotNull();
        }
    }
}
