/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.Marcas;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MarcasRecord extends UpdatableRecordImpl<MarcasRecord> implements Record4<Integer, String, Byte, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.marcas.id</code>.
     */
    public MarcasRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.marcas.nombre</code>.
     */
    public MarcasRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.marcas.activo</code>.
     */
    public MarcasRecord setActivo(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.marcas.fecha_creacion</code>.
     */
    public MarcasRecord setFechaCreacion(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Byte, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Byte, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Marcas.MARCAS.ID;
    }

    @Override
    public Field<String> field2() {
        return Marcas.MARCAS.NOMBRE;
    }

    @Override
    public Field<Byte> field3() {
        return Marcas.MARCAS.ACTIVO;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Marcas.MARCAS.FECHA_CREACION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public Byte component3() {
        return getActivo();
    }

    @Override
    public LocalDateTime component4() {
        return getFechaCreacion();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public Byte value3() {
        return getActivo();
    }

    @Override
    public LocalDateTime value4() {
        return getFechaCreacion();
    }

    @Override
    public MarcasRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MarcasRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public MarcasRecord value3(Byte value) {
        setActivo(value);
        return this;
    }

    @Override
    public MarcasRecord value4(LocalDateTime value) {
        setFechaCreacion(value);
        return this;
    }

    @Override
    public MarcasRecord values(Integer value1, String value2, Byte value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarcasRecord
     */
    public MarcasRecord() {
        super(Marcas.MARCAS);
    }

    /**
     * Create a detached, initialised MarcasRecord
     */
    public MarcasRecord(Integer id, String nombre, Byte activo, LocalDateTime fechaCreacion) {
        super(Marcas.MARCAS);

        setId(id);
        setNombre(nombre);
        setActivo(activo);
        setFechaCreacion(fechaCreacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MarcasRecord
     */
    public MarcasRecord(com.rodiejacontable.database.jooq.tables.pojos.Marcas value) {
        super(Marcas.MARCAS);

        if (value != null) {
            setId(value.getId());
            setNombre(value.getNombre());
            setActivo(value.getActivo());
            setFechaCreacion(value.getFechaCreacion());
            resetChangedOnNotNull();
        }
    }
}
