/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.Modelos;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ModelosRecord extends UpdatableRecordImpl<ModelosRecord> implements Record5<Integer, Integer, String, Byte, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.modelos.id</code>.
     */
    public ModelosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.marca_id</code>.
     */
    public ModelosRecord setMarcaId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.marca_id</code>.
     */
    public Integer getMarcaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.nombre</code>.
     */
    public ModelosRecord setNombre(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.nombre</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.activo</code>.
     */
    public ModelosRecord setActivo(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.fecha_creacion</code>.
     */
    public ModelosRecord setFechaCreacion(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Byte, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Byte, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Modelos.MODELOS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Modelos.MODELOS.MARCA_ID;
    }

    @Override
    public Field<String> field3() {
        return Modelos.MODELOS.NOMBRE;
    }

    @Override
    public Field<Byte> field4() {
        return Modelos.MODELOS.ACTIVO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Modelos.MODELOS.FECHA_CREACION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMarcaId();
    }

    @Override
    public String component3() {
        return getNombre();
    }

    @Override
    public Byte component4() {
        return getActivo();
    }

    @Override
    public LocalDateTime component5() {
        return getFechaCreacion();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMarcaId();
    }

    @Override
    public String value3() {
        return getNombre();
    }

    @Override
    public Byte value4() {
        return getActivo();
    }

    @Override
    public LocalDateTime value5() {
        return getFechaCreacion();
    }

    @Override
    public ModelosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ModelosRecord value2(Integer value) {
        setMarcaId(value);
        return this;
    }

    @Override
    public ModelosRecord value3(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public ModelosRecord value4(Byte value) {
        setActivo(value);
        return this;
    }

    @Override
    public ModelosRecord value5(LocalDateTime value) {
        setFechaCreacion(value);
        return this;
    }

    @Override
    public ModelosRecord values(Integer value1, Integer value2, String value3, Byte value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelosRecord
     */
    public ModelosRecord() {
        super(Modelos.MODELOS);
    }

    /**
     * Create a detached, initialised ModelosRecord
     */
    public ModelosRecord(Integer id, Integer marcaId, String nombre, Byte activo, LocalDateTime fechaCreacion) {
        super(Modelos.MODELOS);

        setId(id);
        setMarcaId(marcaId);
        setNombre(nombre);
        setActivo(activo);
        setFechaCreacion(fechaCreacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ModelosRecord
     */
    public ModelosRecord(com.rodiejacontable.database.jooq.tables.pojos.Modelos value) {
        super(Modelos.MODELOS);

        if (value != null) {
            setId(value.getId());
            setMarcaId(value.getMarcaId());
            setNombre(value.getNombre());
            setActivo(value.getActivo());
            setFechaCreacion(value.getFechaCreacion());
            resetChangedOnNotNull();
        }
    }
}
