/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.Modulos;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModulosRecord extends UpdatableRecordImpl<ModulosRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.modulos.id</code>.
     */
    public ModulosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modulos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.modulos.nombre</code>.
     */
    public ModulosRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modulos.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.modulos.clave</code>.
     */
    public ModulosRecord setClave(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modulos.clave</code>.
     */
    public String getClave() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.modulos.icono</code>.
     */
    public ModulosRecord setIcono(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modulos.icono</code>.
     */
    public String getIcono() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Modulos.MODULOS.ID;
    }

    @Override
    public Field<String> field2() {
        return Modulos.MODULOS.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return Modulos.MODULOS.CLAVE;
    }

    @Override
    public Field<String> field4() {
        return Modulos.MODULOS.ICONO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getClave();
    }

    @Override
    public String component4() {
        return getIcono();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getClave();
    }

    @Override
    public String value4() {
        return getIcono();
    }

    @Override
    public ModulosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ModulosRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public ModulosRecord value3(String value) {
        setClave(value);
        return this;
    }

    @Override
    public ModulosRecord value4(String value) {
        setIcono(value);
        return this;
    }

    @Override
    public ModulosRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModulosRecord
     */
    public ModulosRecord() {
        super(Modulos.MODULOS);
    }

    /**
     * Create a detached, initialised ModulosRecord
     */
    public ModulosRecord(Integer id, String nombre, String clave, String icono) {
        super(Modulos.MODULOS);

        setId(id);
        setNombre(nombre);
        setClave(clave);
        setIcono(icono);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ModulosRecord
     */
    public ModulosRecord(com.rodiejacontable.database.jooq.tables.pojos.Modulos value) {
        super(Modulos.MODULOS);

        if (value != null) {
            setId(value.getId());
            setNombre(value.getNombre());
            setClave(value.getClave());
            setIcono(value.getIcono());
            resetChangedOnNotNull();
        }
    }
}
