/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.PersonalData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalDataRecord extends UpdatableRecordImpl<PersonalDataRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.personal_data.user_id</code>.
     */
    public PersonalDataRecord setUserId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.personal_data.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.personal_data.full_name</code>.
     */
    public PersonalDataRecord setFullName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.personal_data.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PersonalData.PERSONAL_DATA.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return PersonalData.PERSONAL_DATA.FULL_NAME;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getFullName();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getFullName();
    }

    @Override
    public PersonalDataRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public PersonalDataRecord value2(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public PersonalDataRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonalDataRecord
     */
    public PersonalDataRecord() {
        super(PersonalData.PERSONAL_DATA);
    }

    /**
     * Create a detached, initialised PersonalDataRecord
     */
    public PersonalDataRecord(Integer userId, String fullName) {
        super(PersonalData.PERSONAL_DATA);

        setUserId(userId);
        setFullName(fullName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PersonalDataRecord
     */
    public PersonalDataRecord(com.rodiejacontable.database.jooq.tables.pojos.PersonalData value) {
        super(PersonalData.PERSONAL_DATA);

        if (value != null) {
            setUserId(value.getUserId());
            setFullName(value.getFullName());
            resetChangedOnNotNull();
        }
    }
}
