/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.Phones;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhonesRecord extends UpdatableRecordImpl<PhonesRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.phones.user_id</code>.
     */
    public PhonesRecord setUserId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.phones.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.phones.whatsapp</code>.
     */
    public PhonesRecord setWhatsapp(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.phones.whatsapp</code>.
     */
    public String getWhatsapp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.phones.other_numbers</code>.
     */
    public PhonesRecord setOtherNumbers(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.phones.other_numbers</code>.
     */
    public String getOtherNumbers() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Phones.PHONES.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return Phones.PHONES.WHATSAPP;
    }

    @Override
    public Field<String> field3() {
        return Phones.PHONES.OTHER_NUMBERS;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getWhatsapp();
    }

    @Override
    public String component3() {
        return getOtherNumbers();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getWhatsapp();
    }

    @Override
    public String value3() {
        return getOtherNumbers();
    }

    @Override
    public PhonesRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public PhonesRecord value2(String value) {
        setWhatsapp(value);
        return this;
    }

    @Override
    public PhonesRecord value3(String value) {
        setOtherNumbers(value);
        return this;
    }

    @Override
    public PhonesRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhonesRecord
     */
    public PhonesRecord() {
        super(Phones.PHONES);
    }

    /**
     * Create a detached, initialised PhonesRecord
     */
    public PhonesRecord(Integer userId, String whatsapp, String otherNumbers) {
        super(Phones.PHONES);

        setUserId(userId);
        setWhatsapp(whatsapp);
        setOtherNumbers(otherNumbers);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PhonesRecord
     */
    public PhonesRecord(com.rodiejacontable.database.jooq.tables.pojos.Phones value) {
        super(Phones.PHONES);

        if (value != null) {
            setUserId(value.getUserId());
            setWhatsapp(value.getWhatsapp());
            setOtherNumbers(value.getOtherNumbers());
            resetChangedOnNotNull();
        }
    }
}
