/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.TiposTransaccionesCategoria;
import com.rodiejacontable.database.jooq.tables.TiposTransacciones;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TiposTransaccionesRecord extends UpdatableRecordImpl<TiposTransaccionesRecord> implements Record5<Integer, String, String, TiposTransaccionesCategoria, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.tipos_transacciones.id</code>.
     */
    public TiposTransaccionesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.tipos_transacciones.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.tipos_transacciones.nombre</code>.
     */
    public TiposTransaccionesRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.tipos_transacciones.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.tipos_transacciones.descripcion</code>.
     */
    public TiposTransaccionesRecord setDescripcion(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.tipos_transacciones.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.tipos_transacciones.categoria</code>.
     */
    public TiposTransaccionesRecord setCategoria(TiposTransaccionesCategoria value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.tipos_transacciones.categoria</code>.
     */
    public TiposTransaccionesCategoria getCategoria() {
        return (TiposTransaccionesCategoria) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.tipos_transacciones.activo</code>.
     */
    public TiposTransaccionesRecord setActivo(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.tipos_transacciones.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, TiposTransaccionesCategoria, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, TiposTransaccionesCategoria, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TiposTransacciones.TIPOS_TRANSACCIONES.ID;
    }

    @Override
    public Field<String> field2() {
        return TiposTransacciones.TIPOS_TRANSACCIONES.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return TiposTransacciones.TIPOS_TRANSACCIONES.DESCRIPCION;
    }

    @Override
    public Field<TiposTransaccionesCategoria> field4() {
        return TiposTransacciones.TIPOS_TRANSACCIONES.CATEGORIA;
    }

    @Override
    public Field<Byte> field5() {
        return TiposTransacciones.TIPOS_TRANSACCIONES.ACTIVO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getDescripcion();
    }

    @Override
    public TiposTransaccionesCategoria component4() {
        return getCategoria();
    }

    @Override
    public Byte component5() {
        return getActivo();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getDescripcion();
    }

    @Override
    public TiposTransaccionesCategoria value4() {
        return getCategoria();
    }

    @Override
    public Byte value5() {
        return getActivo();
    }

    @Override
    public TiposTransaccionesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TiposTransaccionesRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public TiposTransaccionesRecord value3(String value) {
        setDescripcion(value);
        return this;
    }

    @Override
    public TiposTransaccionesRecord value4(TiposTransaccionesCategoria value) {
        setCategoria(value);
        return this;
    }

    @Override
    public TiposTransaccionesRecord value5(Byte value) {
        setActivo(value);
        return this;
    }

    @Override
    public TiposTransaccionesRecord values(Integer value1, String value2, String value3, TiposTransaccionesCategoria value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TiposTransaccionesRecord
     */
    public TiposTransaccionesRecord() {
        super(TiposTransacciones.TIPOS_TRANSACCIONES);
    }

    /**
     * Create a detached, initialised TiposTransaccionesRecord
     */
    public TiposTransaccionesRecord(Integer id, String nombre, String descripcion, TiposTransaccionesCategoria categoria, Byte activo) {
        super(TiposTransacciones.TIPOS_TRANSACCIONES);

        setId(id);
        setNombre(nombre);
        setDescripcion(descripcion);
        setCategoria(categoria);
        setActivo(activo);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TiposTransaccionesRecord
     */
    public TiposTransaccionesRecord(com.rodiejacontable.database.jooq.tables.pojos.TiposTransacciones value) {
        super(TiposTransacciones.TIPOS_TRANSACCIONES);

        if (value != null) {
            setId(value.getId());
            setNombre(value.getNombre());
            setDescripcion(value.getDescripcion());
            setCategoria(value.getCategoria());
            setActivo(value.getActivo());
            resetChangedOnNotNull();
        }
    }
}
