/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.VehiculosCombustible;
import com.rodiejacontable.database.jooq.enums.VehiculosEstado;
import com.rodiejacontable.database.jooq.enums.VehiculosTraccion;
import com.rodiejacontable.database.jooq.enums.VehiculosTransmision;
import com.rodiejacontable.database.jooq.tables.Vehiculos;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehiculosRecord extends UpdatableRecordImpl<VehiculosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.vehiculos.id</code>.
     */
    public VehiculosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.codigo_vehiculo</code>.
     */
    public VehiculosRecord setCodigoVehiculo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.generacion_id</code>.
     */
    public VehiculosRecord setGeneracionId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.imagen_url</code>.
     */
    public VehiculosRecord setImagenUrl(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.imagen_url</code>.
     */
    public String getImagenUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.anio</code>.
     */
    public VehiculosRecord setAnio(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.anio</code>.
     */
    public Integer getAnio() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.precio_compra</code>.
     */
    public VehiculosRecord setPrecioCompra(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.precio_compra</code>.
     */
    public BigDecimal getPrecioCompra() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_grua</code>.
     */
    public VehiculosRecord setCostoGrua(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_grua</code>.
     */
    public BigDecimal getCostoGrua() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.comisiones</code>.
     */
    public VehiculosRecord setComisiones(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.comisiones</code>.
     */
    public BigDecimal getComisiones() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.inversion_total</code>.
     */
    public VehiculosRecord setInversionTotal(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.inversion_total</code>.
     */
    public BigDecimal getInversionTotal() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_recuperado</code>.
     */
    public VehiculosRecord setCostoRecuperado(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_recuperado</code>.
     */
    public BigDecimal getCostoRecuperado() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_pendiente</code>.
     */
    public VehiculosRecord setCostoPendiente(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_pendiente</code>.
     */
    public BigDecimal getCostoPendiente() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.traccion</code>.
     */
    public VehiculosRecord setTraccion(VehiculosTraccion value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.traccion</code>.
     */
    public VehiculosTraccion getTraccion() {
        return (VehiculosTraccion) get(11);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.transmision</code>.
     */
    public VehiculosRecord setTransmision(VehiculosTransmision value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.transmision</code>.
     */
    public VehiculosTransmision getTransmision() {
        return (VehiculosTransmision) get(12);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.combustible</code>.
     */
    public VehiculosRecord setCombustible(VehiculosCombustible value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.combustible</code>.
     */
    public VehiculosCombustible getCombustible() {
        return (VehiculosCombustible) get(13);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.cilindraje</code>.
     */
    public VehiculosRecord setCilindraje(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.cilindraje</code>.
     */
    public String getCilindraje() {
        return (String) get(14);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_ingreso</code>.
     */
    public VehiculosRecord setFechaIngreso(LocalDate value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_ingreso</code>.
     */
    public LocalDate getFechaIngreso() {
        return (LocalDate) get(15);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.estado</code>.
     */
    public VehiculosRecord setEstado(VehiculosEstado value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.estado</code>.
     */
    public VehiculosEstado getEstado() {
        return (VehiculosEstado) get(16);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.precio_venta</code>.
     */
    public VehiculosRecord setPrecioVenta(BigDecimal value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_venta</code>.
     */
    public VehiculosRecord setFechaVenta(LocalDate value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_venta</code>.
     */
    public LocalDate getFechaVenta() {
        return (LocalDate) get(18);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.activo</code>.
     */
    public VehiculosRecord setActivo(Byte value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.notas</code>.
     */
    public VehiculosRecord setNotas(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.notas</code>.
     */
    public String getNotas() {
        return (String) get(20);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_creacion</code>.
     */
    public VehiculosRecord setFechaCreacion(LocalDateTime value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_actualizacion</code>.
     */
    public VehiculosRecord setFechaActualizacion(LocalDateTime value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return (LocalDateTime) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehiculosRecord
     */
    public VehiculosRecord() {
        super(Vehiculos.VEHICULOS);
    }

    /**
     * Create a detached, initialised VehiculosRecord
     */
    public VehiculosRecord(Integer id, String codigoVehiculo, Integer generacionId, String imagenUrl, Integer anio, BigDecimal precioCompra, BigDecimal costoGrua, BigDecimal comisiones, BigDecimal inversionTotal, BigDecimal costoRecuperado, BigDecimal costoPendiente, VehiculosTraccion traccion, VehiculosTransmision transmision, VehiculosCombustible combustible, String cilindraje, LocalDate fechaIngreso, VehiculosEstado estado, BigDecimal precioVenta, LocalDate fechaVenta, Byte activo, String notas, LocalDateTime fechaCreacion, LocalDateTime fechaActualizacion) {
        super(Vehiculos.VEHICULOS);

        setId(id);
        setCodigoVehiculo(codigoVehiculo);
        setGeneracionId(generacionId);
        setImagenUrl(imagenUrl);
        setAnio(anio);
        setPrecioCompra(precioCompra);
        setCostoGrua(costoGrua);
        setComisiones(comisiones);
        setInversionTotal(inversionTotal);
        setCostoRecuperado(costoRecuperado);
        setCostoPendiente(costoPendiente);
        setTraccion(traccion);
        setTransmision(transmision);
        setCombustible(combustible);
        setCilindraje(cilindraje);
        setFechaIngreso(fechaIngreso);
        setEstado(estado);
        setPrecioVenta(precioVenta);
        setFechaVenta(fechaVenta);
        setActivo(activo);
        setNotas(notas);
        setFechaCreacion(fechaCreacion);
        setFechaActualizacion(fechaActualizacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VehiculosRecord
     */
    public VehiculosRecord(com.rodiejacontable.database.jooq.tables.pojos.Vehiculos value) {
        super(Vehiculos.VEHICULOS);

        if (value != null) {
            setId(value.getId());
            setCodigoVehiculo(value.getCodigoVehiculo());
            setGeneracionId(value.getGeneracionId());
            setImagenUrl(value.getImagenUrl());
            setAnio(value.getAnio());
            setPrecioCompra(value.getPrecioCompra());
            setCostoGrua(value.getCostoGrua());
            setComisiones(value.getComisiones());
            setInversionTotal(value.getInversionTotal());
            setCostoRecuperado(value.getCostoRecuperado());
            setCostoPendiente(value.getCostoPendiente());
            setTraccion(value.getTraccion());
            setTransmision(value.getTransmision());
            setCombustible(value.getCombustible());
            setCilindraje(value.getCilindraje());
            setFechaIngreso(value.getFechaIngreso());
            setEstado(value.getEstado());
            setPrecioVenta(value.getPrecioVenta());
            setFechaVenta(value.getFechaVenta());
            setActivo(value.getActivo());
            setNotas(value.getNotas());
            setFechaCreacion(value.getFechaCreacion());
            setFechaActualizacion(value.getFechaActualizacion());
            resetChangedOnNotNull();
        }
    }
}
