/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.VistaInventarioCriticoEstado;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCriticoParteVehiculo;
import com.rodiejacontable.database.jooq.tables.VistaInventarioCritico;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaInventarioCriticoRecord extends TableRecordImpl<VistaInventarioCriticoRecord> implements Record17<String, VistaInventarioCriticoParteVehiculo, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, VistaInventarioCriticoEstado, String, String, Integer, Short, Byte, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_repuesto</code>.
     */
    public VistaInventarioCriticoRecord setCodigoRepuesto(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_repuesto</code>.
     */
    public String getCodigoRepuesto() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.parte_vehiculo</code>.
     */
    public VistaInventarioCriticoRecord setParteVehiculo(VistaInventarioCriticoParteVehiculo value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.parte_vehiculo</code>.
     */
    public VistaInventarioCriticoParteVehiculo getParteVehiculo() {
        return (VistaInventarioCriticoParteVehiculo) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.descripcion</code>.
     */
    public VistaInventarioCriticoRecord setDescripcion(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_costo</code>.
     */
    public VistaInventarioCriticoRecord setPrecioCosto(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_costo</code>.
     */
    public BigDecimal getPrecioCosto() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_venta</code>.
     */
    public VistaInventarioCriticoRecord setPrecioVenta(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_mayoreo</code>.
     */
    public VistaInventarioCriticoRecord setPrecioMayoreo(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_mayoreo</code>.
     */
    public BigDecimal getPrecioMayoreo() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_15</code>.
     */
    public VistaInventarioCriticoRecord setFormula_15(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_15</code>.
     */
    public BigDecimal getFormula_15() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_30</code>.
     */
    public VistaInventarioCriticoRecord setFormula_30(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_30</code>.
     */
    public BigDecimal getFormula_30() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.estado</code>.
     */
    public VistaInventarioCriticoRecord setEstado(VistaInventarioCriticoEstado value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.estado</code>.
     */
    public VistaInventarioCriticoEstado getEstado() {
        return (VistaInventarioCriticoEstado) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_ubicacion</code>.
     */
    public VistaInventarioCriticoRecord setCodigoUbicacion(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_ubicacion</code>.
     */
    public String getCodigoUbicacion() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.vehiculo_origen</code>.
     */
    public VistaInventarioCriticoRecord setVehiculoOrigen(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.vehiculo_origen</code>.
     */
    public String getVehiculoOrigen() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_vehiculo</code>.
     */
    public VistaInventarioCriticoRecord setAnioVehiculo(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_vehiculo</code>.
     */
    public Integer getAnioVehiculo() {
        return (Integer) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_registro</code>.
     */
    public VistaInventarioCriticoRecord setAnioRegistro(Short value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_registro</code>.
     */
    public Short getAnioRegistro() {
        return (Short) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.mes_registro</code>.
     */
    public VistaInventarioCriticoRecord setMesRegistro(Byte value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.mes_registro</code>.
     */
    public Byte getMesRegistro() {
        return (Byte) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.dias_en_inventario</code>.
     */
    public VistaInventarioCriticoRecord setDiasEnInventario(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.dias_en_inventario</code>.
     */
    public Integer getDiasEnInventario() {
        return (Integer) get(14);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_margen</code>.
     */
    public VistaInventarioCriticoRecord setClasificacionMargen(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_margen</code>.
     */
    public String getClasificacionMargen() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_rotacion</code>.
     */
    public VistaInventarioCriticoRecord setClasificacionRotacion(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_rotacion</code>.
     */
    public String getClasificacionRotacion() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<String, VistaInventarioCriticoParteVehiculo, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, VistaInventarioCriticoEstado, String, String, Integer, Short, Byte, Integer, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<String, VistaInventarioCriticoParteVehiculo, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, VistaInventarioCriticoEstado, String, String, Integer, Short, Byte, Integer, String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.CODIGO_REPUESTO;
    }

    @Override
    public Field<VistaInventarioCriticoParteVehiculo> field2() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.PARTE_VEHICULO;
    }

    @Override
    public Field<String> field3() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.DESCRIPCION;
    }

    @Override
    public Field<BigDecimal> field4() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.PRECIO_COSTO;
    }

    @Override
    public Field<BigDecimal> field5() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.PRECIO_VENTA;
    }

    @Override
    public Field<BigDecimal> field6() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.PRECIO_MAYOREO;
    }

    @Override
    public Field<BigDecimal> field7() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.FORMULA_15;
    }

    @Override
    public Field<BigDecimal> field8() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.FORMULA_30;
    }

    @Override
    public Field<VistaInventarioCriticoEstado> field9() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.ESTADO;
    }

    @Override
    public Field<String> field10() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.CODIGO_UBICACION;
    }

    @Override
    public Field<String> field11() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.VEHICULO_ORIGEN;
    }

    @Override
    public Field<Integer> field12() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.ANIO_VEHICULO;
    }

    @Override
    public Field<Short> field13() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.ANIO_REGISTRO;
    }

    @Override
    public Field<Byte> field14() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.MES_REGISTRO;
    }

    @Override
    public Field<Integer> field15() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.DIAS_EN_INVENTARIO;
    }

    @Override
    public Field<String> field16() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.CLASIFICACION_MARGEN;
    }

    @Override
    public Field<String> field17() {
        return VistaInventarioCritico.VISTA_INVENTARIO_CRITICO.CLASIFICACION_ROTACION;
    }

    @Override
    public String component1() {
        return getCodigoRepuesto();
    }

    @Override
    public VistaInventarioCriticoParteVehiculo component2() {
        return getParteVehiculo();
    }

    @Override
    public String component3() {
        return getDescripcion();
    }

    @Override
    public BigDecimal component4() {
        return getPrecioCosto();
    }

    @Override
    public BigDecimal component5() {
        return getPrecioVenta();
    }

    @Override
    public BigDecimal component6() {
        return getPrecioMayoreo();
    }

    @Override
    public BigDecimal component7() {
        return getFormula_15();
    }

    @Override
    public BigDecimal component8() {
        return getFormula_30();
    }

    @Override
    public VistaInventarioCriticoEstado component9() {
        return getEstado();
    }

    @Override
    public String component10() {
        return getCodigoUbicacion();
    }

    @Override
    public String component11() {
        return getVehiculoOrigen();
    }

    @Override
    public Integer component12() {
        return getAnioVehiculo();
    }

    @Override
    public Short component13() {
        return getAnioRegistro();
    }

    @Override
    public Byte component14() {
        return getMesRegistro();
    }

    @Override
    public Integer component15() {
        return getDiasEnInventario();
    }

    @Override
    public String component16() {
        return getClasificacionMargen();
    }

    @Override
    public String component17() {
        return getClasificacionRotacion();
    }

    @Override
    public String value1() {
        return getCodigoRepuesto();
    }

    @Override
    public VistaInventarioCriticoParteVehiculo value2() {
        return getParteVehiculo();
    }

    @Override
    public String value3() {
        return getDescripcion();
    }

    @Override
    public BigDecimal value4() {
        return getPrecioCosto();
    }

    @Override
    public BigDecimal value5() {
        return getPrecioVenta();
    }

    @Override
    public BigDecimal value6() {
        return getPrecioMayoreo();
    }

    @Override
    public BigDecimal value7() {
        return getFormula_15();
    }

    @Override
    public BigDecimal value8() {
        return getFormula_30();
    }

    @Override
    public VistaInventarioCriticoEstado value9() {
        return getEstado();
    }

    @Override
    public String value10() {
        return getCodigoUbicacion();
    }

    @Override
    public String value11() {
        return getVehiculoOrigen();
    }

    @Override
    public Integer value12() {
        return getAnioVehiculo();
    }

    @Override
    public Short value13() {
        return getAnioRegistro();
    }

    @Override
    public Byte value14() {
        return getMesRegistro();
    }

    @Override
    public Integer value15() {
        return getDiasEnInventario();
    }

    @Override
    public String value16() {
        return getClasificacionMargen();
    }

    @Override
    public String value17() {
        return getClasificacionRotacion();
    }

    @Override
    public VistaInventarioCriticoRecord value1(String value) {
        setCodigoRepuesto(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value2(VistaInventarioCriticoParteVehiculo value) {
        setParteVehiculo(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value3(String value) {
        setDescripcion(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value4(BigDecimal value) {
        setPrecioCosto(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value5(BigDecimal value) {
        setPrecioVenta(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value6(BigDecimal value) {
        setPrecioMayoreo(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value7(BigDecimal value) {
        setFormula_15(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value8(BigDecimal value) {
        setFormula_30(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value9(VistaInventarioCriticoEstado value) {
        setEstado(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value10(String value) {
        setCodigoUbicacion(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value11(String value) {
        setVehiculoOrigen(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value12(Integer value) {
        setAnioVehiculo(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value13(Short value) {
        setAnioRegistro(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value14(Byte value) {
        setMesRegistro(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value15(Integer value) {
        setDiasEnInventario(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value16(String value) {
        setClasificacionMargen(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord value17(String value) {
        setClasificacionRotacion(value);
        return this;
    }

    @Override
    public VistaInventarioCriticoRecord values(String value1, VistaInventarioCriticoParteVehiculo value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, VistaInventarioCriticoEstado value9, String value10, String value11, Integer value12, Short value13, Byte value14, Integer value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaInventarioCriticoRecord
     */
    public VistaInventarioCriticoRecord() {
        super(VistaInventarioCritico.VISTA_INVENTARIO_CRITICO);
    }

    /**
     * Create a detached, initialised VistaInventarioCriticoRecord
     */
    public VistaInventarioCriticoRecord(String codigoRepuesto, VistaInventarioCriticoParteVehiculo parteVehiculo, String descripcion, BigDecimal precioCosto, BigDecimal precioVenta, BigDecimal precioMayoreo, BigDecimal formula_15, BigDecimal formula_30, VistaInventarioCriticoEstado estado, String codigoUbicacion, String vehiculoOrigen, Integer anioVehiculo, Short anioRegistro, Byte mesRegistro, Integer diasEnInventario, String clasificacionMargen, String clasificacionRotacion) {
        super(VistaInventarioCritico.VISTA_INVENTARIO_CRITICO);

        setCodigoRepuesto(codigoRepuesto);
        setParteVehiculo(parteVehiculo);
        setDescripcion(descripcion);
        setPrecioCosto(precioCosto);
        setPrecioVenta(precioVenta);
        setPrecioMayoreo(precioMayoreo);
        setFormula_15(formula_15);
        setFormula_30(formula_30);
        setEstado(estado);
        setCodigoUbicacion(codigoUbicacion);
        setVehiculoOrigen(vehiculoOrigen);
        setAnioVehiculo(anioVehiculo);
        setAnioRegistro(anioRegistro);
        setMesRegistro(mesRegistro);
        setDiasEnInventario(diasEnInventario);
        setClasificacionMargen(clasificacionMargen);
        setClasificacionRotacion(clasificacionRotacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaInventarioCriticoRecord
     */
    public VistaInventarioCriticoRecord(com.rodiejacontable.database.jooq.tables.pojos.VistaInventarioCritico value) {
        super(VistaInventarioCritico.VISTA_INVENTARIO_CRITICO);

        if (value != null) {
            setCodigoRepuesto(value.getCodigoRepuesto());
            setParteVehiculo(value.getParteVehiculo());
            setDescripcion(value.getDescripcion());
            setPrecioCosto(value.getPrecioCosto());
            setPrecioVenta(value.getPrecioVenta());
            setPrecioMayoreo(value.getPrecioMayoreo());
            setFormula_15(value.getFormula_15());
            setFormula_30(value.getFormula_30());
            setEstado(value.getEstado());
            setCodigoUbicacion(value.getCodigoUbicacion());
            setVehiculoOrigen(value.getVehiculoOrigen());
            setAnioVehiculo(value.getAnioVehiculo());
            setAnioRegistro(value.getAnioRegistro());
            setMesRegistro(value.getMesRegistro());
            setDiasEnInventario(value.getDiasEnInventario());
            setClasificacionMargen(value.getClasificacionMargen());
            setClasificacionRotacion(value.getClasificacionRotacion());
            resetChangedOnNotNull();
        }
    }
}
