/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.VistaVehiculosCompletaCombustible;
import com.rodiejacontable.database.jooq.enums.VistaVehiculosCompletaEstado;
import com.rodiejacontable.database.jooq.enums.VistaVehiculosCompletaTraccion;
import com.rodiejacontable.database.jooq.enums.VistaVehiculosCompletaTransmision;
import com.rodiejacontable.database.jooq.tables.VistaVehiculosCompleta;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaVehiculosCompletaRecord extends TableRecordImpl<VistaVehiculosCompletaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.id</code>.
     */
    public VistaVehiculosCompletaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.codigo_vehiculo</code>.
     */
    public VistaVehiculosCompletaRecord setCodigoVehiculo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.anio</code>.
     */
    public VistaVehiculosCompletaRecord setAnio(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.anio</code>.
     */
    public Integer getAnio() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_compra</code>.
     */
    public VistaVehiculosCompletaRecord setPrecioCompra(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_compra</code>.
     */
    public BigDecimal getPrecioCompra() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.costo_grua</code>.
     */
    public VistaVehiculosCompletaRecord setCostoGrua(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.costo_grua</code>.
     */
    public BigDecimal getCostoGrua() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.comisiones</code>.
     */
    public VistaVehiculosCompletaRecord setComisiones(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.comisiones</code>.
     */
    public BigDecimal getComisiones() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.inversion_total</code>.
     */
    public VistaVehiculosCompletaRecord setInversionTotal(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.inversion_total</code>.
     */
    public BigDecimal getInversionTotal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_venta</code>.
     */
    public VistaVehiculosCompletaRecord setPrecioVenta(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_ingreso</code>.
     */
    public VistaVehiculosCompletaRecord setFechaIngreso(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_ingreso</code>.
     */
    public LocalDate getFechaIngreso() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_venta</code>.
     */
    public VistaVehiculosCompletaRecord setFechaVenta(LocalDate value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_venta</code>.
     */
    public LocalDate getFechaVenta() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.estado</code>.
     */
    public VistaVehiculosCompletaRecord setEstado(VistaVehiculosCompletaEstado value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.estado</code>.
     */
    public VistaVehiculosCompletaEstado getEstado() {
        return (VistaVehiculosCompletaEstado) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.activo</code>.
     */
    public VistaVehiculosCompletaRecord setActivo(Byte value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.notas</code>.
     */
    public VistaVehiculosCompletaRecord setNotas(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.notas</code>.
     */
    public String getNotas() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.traccion</code>.
     */
    public VistaVehiculosCompletaRecord setTraccion(VistaVehiculosCompletaTraccion value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.traccion</code>.
     */
    public VistaVehiculosCompletaTraccion getTraccion() {
        return (VistaVehiculosCompletaTraccion) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.transmision</code>.
     */
    public VistaVehiculosCompletaRecord setTransmision(VistaVehiculosCompletaTransmision value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.transmision</code>.
     */
    public VistaVehiculosCompletaTransmision getTransmision() {
        return (VistaVehiculosCompletaTransmision) get(14);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.combustible</code>.
     */
    public VistaVehiculosCompletaRecord setCombustible(VistaVehiculosCompletaCombustible value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.combustible</code>.
     */
    public VistaVehiculosCompletaCombustible getCombustible() {
        return (VistaVehiculosCompletaCombustible) get(15);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.cilindraje</code>.
     */
    public VistaVehiculosCompletaRecord setCilindraje(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.cilindraje</code>.
     */
    public String getCilindraje() {
        return (String) get(16);
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.marca</code>.
     */
    public VistaVehiculosCompletaRecord setMarca(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.marca</code>.
     */
    public String getMarca() {
        return (String) get(17);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.modelo</code>.
     */
    public VistaVehiculosCompletaRecord setModelo(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.modelo</code>.
     */
    public String getModelo() {
        return (String) get(18);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion</code>.
     */
    public VistaVehiculosCompletaRecord setGeneracion(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion</code>.
     */
    public String getGeneracion() {
        return (String) get(19);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion_descripcion</code>.
     */
    public VistaVehiculosCompletaRecord setGeneracionDescripcion(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion_descripcion</code>.
     */
    public String getGeneracionDescripcion() {
        return (String) get(20);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_inicio</code>.
     */
    public VistaVehiculosCompletaRecord setAnioInicio(Integer value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_inicio</code>.
     */
    public Integer getAnioInicio() {
        return (Integer) get(21);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_fin</code>.
     */
    public VistaVehiculosCompletaRecord setAnioFin(Integer value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_fin</code>.
     */
    public Integer getAnioFin() {
        return (Integer) get(22);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.clave_generacion</code>.
     */
    public VistaVehiculosCompletaRecord setClaveGeneracion(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return (String) get(23);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_ingresos_vehiculo</code>.
     */
    public VistaVehiculosCompletaRecord setTotalIngresosVehiculo(BigDecimal value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_ingresos_vehiculo</code>.
     */
    public BigDecimal getTotalIngresosVehiculo() {
        return (BigDecimal) get(24);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_egresos_vehiculo</code>.
     */
    public VistaVehiculosCompletaRecord setTotalEgresosVehiculo(BigDecimal value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_egresos_vehiculo</code>.
     */
    public BigDecimal getTotalEgresosVehiculo() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.balance_neto_vehiculo</code>.
     */
    public VistaVehiculosCompletaRecord setBalanceNetoVehiculo(BigDecimal value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.balance_neto_vehiculo</code>.
     */
    public BigDecimal getBalanceNetoVehiculo() {
        return (BigDecimal) get(26);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaVehiculosCompletaRecord
     */
    public VistaVehiculosCompletaRecord() {
        super(VistaVehiculosCompleta.VISTA_VEHICULOS_COMPLETA);
    }

    /**
     * Create a detached, initialised VistaVehiculosCompletaRecord
     */
    public VistaVehiculosCompletaRecord(Integer id, String codigoVehiculo, Integer anio, BigDecimal precioCompra, BigDecimal costoGrua, BigDecimal comisiones, BigDecimal inversionTotal, BigDecimal precioVenta, LocalDate fechaIngreso, LocalDate fechaVenta, VistaVehiculosCompletaEstado estado, Byte activo, String notas, VistaVehiculosCompletaTraccion traccion, VistaVehiculosCompletaTransmision transmision, VistaVehiculosCompletaCombustible combustible, String cilindraje, String marca, String modelo, String generacion, String generacionDescripcion, Integer anioInicio, Integer anioFin, String claveGeneracion, BigDecimal totalIngresosVehiculo, BigDecimal totalEgresosVehiculo, BigDecimal balanceNetoVehiculo) {
        super(VistaVehiculosCompleta.VISTA_VEHICULOS_COMPLETA);

        setId(id);
        setCodigoVehiculo(codigoVehiculo);
        setAnio(anio);
        setPrecioCompra(precioCompra);
        setCostoGrua(costoGrua);
        setComisiones(comisiones);
        setInversionTotal(inversionTotal);
        setPrecioVenta(precioVenta);
        setFechaIngreso(fechaIngreso);
        setFechaVenta(fechaVenta);
        setEstado(estado);
        setActivo(activo);
        setNotas(notas);
        setTraccion(traccion);
        setTransmision(transmision);
        setCombustible(combustible);
        setCilindraje(cilindraje);
        setMarca(marca);
        setModelo(modelo);
        setGeneracion(generacion);
        setGeneracionDescripcion(generacionDescripcion);
        setAnioInicio(anioInicio);
        setAnioFin(anioFin);
        setClaveGeneracion(claveGeneracion);
        setTotalIngresosVehiculo(totalIngresosVehiculo);
        setTotalEgresosVehiculo(totalEgresosVehiculo);
        setBalanceNetoVehiculo(balanceNetoVehiculo);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaVehiculosCompletaRecord
     */
    public VistaVehiculosCompletaRecord(com.rodiejacontable.database.jooq.tables.pojos.VistaVehiculosCompleta value) {
        super(VistaVehiculosCompleta.VISTA_VEHICULOS_COMPLETA);

        if (value != null) {
            setId(value.getId());
            setCodigoVehiculo(value.getCodigoVehiculo());
            setAnio(value.getAnio());
            setPrecioCompra(value.getPrecioCompra());
            setCostoGrua(value.getCostoGrua());
            setComisiones(value.getComisiones());
            setInversionTotal(value.getInversionTotal());
            setPrecioVenta(value.getPrecioVenta());
            setFechaIngreso(value.getFechaIngreso());
            setFechaVenta(value.getFechaVenta());
            setEstado(value.getEstado());
            setActivo(value.getActivo());
            setNotas(value.getNotas());
            setTraccion(value.getTraccion());
            setTransmision(value.getTransmision());
            setCombustible(value.getCombustible());
            setCilindraje(value.getCilindraje());
            setMarca(value.getMarca());
            setModelo(value.getModelo());
            setGeneracion(value.getGeneracion());
            setGeneracionDescripcion(value.getGeneracionDescripcion());
            setAnioInicio(value.getAnioInicio());
            setAnioFin(value.getAnioFin());
            setClaveGeneracion(value.getClaveGeneracion());
            setTotalIngresosVehiculo(value.getTotalIngresosVehiculo());
            setTotalEgresosVehiculo(value.getTotalEgresosVehiculo());
            setBalanceNetoVehiculo(value.getBalanceNetoVehiculo());
            resetChangedOnNotNull();
        }
    }
}
