/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.VistaResumenGeneraciones;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaResumenGeneracionesRecord extends TableRecordImpl<VistaResumenGeneracionesRecord> implements Record15<Integer, String, String, String, String, String, Integer, Integer, Long, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion_id</code>.
     */
    public VistaResumenGeneracionesRecord setGeneracionId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.marca</code>.
     */
    public VistaResumenGeneracionesRecord setMarca(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.marca</code>.
     */
    public String getMarca() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.modelo</code>.
     */
    public VistaResumenGeneracionesRecord setModelo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.modelo</code>.
     */
    public String getModelo() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion</code>.
     */
    public VistaResumenGeneracionesRecord setGeneracion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion</code>.
     */
    public String getGeneracion() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.descripcion</code>.
     */
    public VistaResumenGeneracionesRecord setDescripcion(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.clave_generacion</code>.
     */
    public VistaResumenGeneracionesRecord setClaveGeneracion(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_inicio</code>.
     */
    public VistaResumenGeneracionesRecord setAnioInicio(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_inicio</code>.
     */
    public Integer getAnioInicio() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_fin</code>.
     */
    public VistaResumenGeneracionesRecord setAnioFin(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_fin</code>.
     */
    public Integer getAnioFin() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_vehiculos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalVehiculos(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_vehiculos</code>.
     */
    public Long getTotalVehiculos() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_repuestos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalRepuestos(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_repuestos</code>.
     */
    public Long getTotalRepuestos() {
        return (Long) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_inversion</code>.
     */
    public VistaResumenGeneracionesRecord setTotalInversion(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_inversion</code>.
     */
    public BigDecimal getTotalInversion() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_ingresos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalIngresos(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_egresos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalEgresos(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_egresos</code>.
     */
    public BigDecimal getTotalEgresos() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.balance_neto</code>.
     */
    public VistaResumenGeneracionesRecord setBalanceNeto(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.balance_neto</code>.
     */
    public BigDecimal getBalanceNeto() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.porcentaje_retorno</code>.
     */
    public VistaResumenGeneracionesRecord setPorcentajeRetorno(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.porcentaje_retorno</code>.
     */
    public BigDecimal getPorcentajeRetorno() {
        return (BigDecimal) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, String, String, String, String, String, Integer, Integer, Long, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, String, String, String, String, String, Integer, Integer, Long, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.GENERACION_ID;
    }

    @Override
    public Field<String> field2() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.MARCA;
    }

    @Override
    public Field<String> field3() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.MODELO;
    }

    @Override
    public Field<String> field4() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.GENERACION;
    }

    @Override
    public Field<String> field5() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.DESCRIPCION;
    }

    @Override
    public Field<String> field6() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.CLAVE_GENERACION;
    }

    @Override
    public Field<Integer> field7() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.ANIO_INICIO;
    }

    @Override
    public Field<Integer> field8() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.ANIO_FIN;
    }

    @Override
    public Field<Long> field9() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.TOTAL_VEHICULOS;
    }

    @Override
    public Field<Long> field10() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.TOTAL_REPUESTOS;
    }

    @Override
    public Field<BigDecimal> field11() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.TOTAL_INVERSION;
    }

    @Override
    public Field<BigDecimal> field12() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.TOTAL_INGRESOS;
    }

    @Override
    public Field<BigDecimal> field13() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.TOTAL_EGRESOS;
    }

    @Override
    public Field<BigDecimal> field14() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.BALANCE_NETO;
    }

    @Override
    public Field<BigDecimal> field15() {
        return VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES.PORCENTAJE_RETORNO;
    }

    @Override
    public Integer component1() {
        return getGeneracionId();
    }

    @Override
    public String component2() {
        return getMarca();
    }

    @Override
    public String component3() {
        return getModelo();
    }

    @Override
    public String component4() {
        return getGeneracion();
    }

    @Override
    public String component5() {
        return getDescripcion();
    }

    @Override
    public String component6() {
        return getClaveGeneracion();
    }

    @Override
    public Integer component7() {
        return getAnioInicio();
    }

    @Override
    public Integer component8() {
        return getAnioFin();
    }

    @Override
    public Long component9() {
        return getTotalVehiculos();
    }

    @Override
    public Long component10() {
        return getTotalRepuestos();
    }

    @Override
    public BigDecimal component11() {
        return getTotalInversion();
    }

    @Override
    public BigDecimal component12() {
        return getTotalIngresos();
    }

    @Override
    public BigDecimal component13() {
        return getTotalEgresos();
    }

    @Override
    public BigDecimal component14() {
        return getBalanceNeto();
    }

    @Override
    public BigDecimal component15() {
        return getPorcentajeRetorno();
    }

    @Override
    public Integer value1() {
        return getGeneracionId();
    }

    @Override
    public String value2() {
        return getMarca();
    }

    @Override
    public String value3() {
        return getModelo();
    }

    @Override
    public String value4() {
        return getGeneracion();
    }

    @Override
    public String value5() {
        return getDescripcion();
    }

    @Override
    public String value6() {
        return getClaveGeneracion();
    }

    @Override
    public Integer value7() {
        return getAnioInicio();
    }

    @Override
    public Integer value8() {
        return getAnioFin();
    }

    @Override
    public Long value9() {
        return getTotalVehiculos();
    }

    @Override
    public Long value10() {
        return getTotalRepuestos();
    }

    @Override
    public BigDecimal value11() {
        return getTotalInversion();
    }

    @Override
    public BigDecimal value12() {
        return getTotalIngresos();
    }

    @Override
    public BigDecimal value13() {
        return getTotalEgresos();
    }

    @Override
    public BigDecimal value14() {
        return getBalanceNeto();
    }

    @Override
    public BigDecimal value15() {
        return getPorcentajeRetorno();
    }

    @Override
    public VistaResumenGeneracionesRecord value1(Integer value) {
        setGeneracionId(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value2(String value) {
        setMarca(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value3(String value) {
        setModelo(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value4(String value) {
        setGeneracion(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value5(String value) {
        setDescripcion(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value6(String value) {
        setClaveGeneracion(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value7(Integer value) {
        setAnioInicio(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value8(Integer value) {
        setAnioFin(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value9(Long value) {
        setTotalVehiculos(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value10(Long value) {
        setTotalRepuestos(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value11(BigDecimal value) {
        setTotalInversion(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value12(BigDecimal value) {
        setTotalIngresos(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value13(BigDecimal value) {
        setTotalEgresos(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value14(BigDecimal value) {
        setBalanceNeto(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord value15(BigDecimal value) {
        setPorcentajeRetorno(value);
        return this;
    }

    @Override
    public VistaResumenGeneracionesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, Long value9, Long value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, BigDecimal value14, BigDecimal value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaResumenGeneracionesRecord
     */
    public VistaResumenGeneracionesRecord() {
        super(VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES);
    }

    /**
     * Create a detached, initialised VistaResumenGeneracionesRecord
     */
    public VistaResumenGeneracionesRecord(Integer generacionId, String marca, String modelo, String generacion, String descripcion, String claveGeneracion, Integer anioInicio, Integer anioFin, Long totalVehiculos, Long totalRepuestos, BigDecimal totalInversion, BigDecimal totalIngresos, BigDecimal totalEgresos, BigDecimal balanceNeto, BigDecimal porcentajeRetorno) {
        super(VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES);

        setGeneracionId(generacionId);
        setMarca(marca);
        setModelo(modelo);
        setGeneracion(generacion);
        setDescripcion(descripcion);
        setClaveGeneracion(claveGeneracion);
        setAnioInicio(anioInicio);
        setAnioFin(anioFin);
        setTotalVehiculos(totalVehiculos);
        setTotalRepuestos(totalRepuestos);
        setTotalInversion(totalInversion);
        setTotalIngresos(totalIngresos);
        setTotalEgresos(totalEgresos);
        setBalanceNeto(balanceNeto);
        setPorcentajeRetorno(porcentajeRetorno);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaResumenGeneracionesRecord
     */
    public VistaResumenGeneracionesRecord(com.rodiejacontable.database.jooq.tables.pojos.VistaResumenGeneraciones value) {
        super(VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES);

        if (value != null) {
            setGeneracionId(value.getGeneracionId());
            setMarca(value.getMarca());
            setModelo(value.getModelo());
            setGeneracion(value.getGeneracion());
            setDescripcion(value.getDescripcion());
            setClaveGeneracion(value.getClaveGeneracion());
            setAnioInicio(value.getAnioInicio());
            setAnioFin(value.getAnioFin());
            setTotalVehiculos(value.getTotalVehiculos());
            setTotalRepuestos(value.getTotalRepuestos());
            setTotalInversion(value.getTotalInversion());
            setTotalIngresos(value.getTotalIngresos());
            setTotalEgresos(value.getTotalEgresos());
            setBalanceNeto(value.getBalanceNeto());
            setPorcentajeRetorno(value.getPorcentajeRetorno());
            resetChangedOnNotNull();
        }
    }
}
