/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private String addressLine1;
    private String addressLine2;
    private String province;
    private String canton;
    private String postalCode;

    public Address() {}

    public Address(Address value) {
        this.userId = value.userId;
        this.addressLine1 = value.addressLine1;
        this.addressLine2 = value.addressLine2;
        this.province = value.province;
        this.canton = value.canton;
        this.postalCode = value.postalCode;
    }

    public Address(
        Integer userId,
        String addressLine1,
        String addressLine2,
        String province,
        String canton,
        String postalCode
    ) {
        this.userId = userId;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.province = province;
        this.canton = canton;
        this.postalCode = postalCode;
    }

    /**
     * Getter for <code>sistema_vehicular.address.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>sistema_vehicular.address.user_id</code>.
     */
    public Address setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.address.address_line1</code>.
     */
    public String getAddressLine1() {
        return this.addressLine1;
    }

    /**
     * Setter for <code>sistema_vehicular.address.address_line1</code>.
     */
    public Address setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.address.address_line2</code>.
     */
    public String getAddressLine2() {
        return this.addressLine2;
    }

    /**
     * Setter for <code>sistema_vehicular.address.address_line2</code>.
     */
    public Address setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.address.province</code>.
     */
    public String getProvince() {
        return this.province;
    }

    /**
     * Setter for <code>sistema_vehicular.address.province</code>.
     */
    public Address setProvince(String province) {
        this.province = province;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.address.canton</code>.
     */
    public String getCanton() {
        return this.canton;
    }

    /**
     * Setter for <code>sistema_vehicular.address.canton</code>.
     */
    public Address setCanton(String canton) {
        this.canton = canton;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.address.postal_code</code>.
     */
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     * Setter for <code>sistema_vehicular.address.postal_code</code>.
     */
    public Address setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Address other = (Address) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.addressLine1 == null) {
            if (other.addressLine1 != null)
                return false;
        }
        else if (!this.addressLine1.equals(other.addressLine1))
            return false;
        if (this.addressLine2 == null) {
            if (other.addressLine2 != null)
                return false;
        }
        else if (!this.addressLine2.equals(other.addressLine2))
            return false;
        if (this.province == null) {
            if (other.province != null)
                return false;
        }
        else if (!this.province.equals(other.province))
            return false;
        if (this.canton == null) {
            if (other.canton != null)
                return false;
        }
        else if (!this.canton.equals(other.canton))
            return false;
        if (this.postalCode == null) {
            if (other.postalCode != null)
                return false;
        }
        else if (!this.postalCode.equals(other.postalCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.addressLine1 == null) ? 0 : this.addressLine1.hashCode());
        result = prime * result + ((this.addressLine2 == null) ? 0 : this.addressLine2.hashCode());
        result = prime * result + ((this.province == null) ? 0 : this.province.hashCode());
        result = prime * result + ((this.canton == null) ? 0 : this.canton.hashCode());
        result = prime * result + ((this.postalCode == null) ? 0 : this.postalCode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(userId);
        sb.append(", ").append(addressLine1);
        sb.append(", ").append(addressLine2);
        sb.append(", ").append(province);
        sb.append(", ").append(canton);
        sb.append(", ").append(postalCode);

        sb.append(")");
        return sb.toString();
    }
}
