/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import com.rodiejacontable.database.jooq.enums.AudatexEnviosEstado;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AudatexEnvios implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer repuestoId;
    private String cotizacionId;
    private String wan;
    private BigDecimal precioOfrecido;
    private String tiempoEntrega;
    private String condicionPieza;
    private AudatexEnviosEstado estado;
    private LocalDateTime fechaEnvio;
    private LocalDateTime fechaActualizacion;
    private String usuarioEnvio;
    private String notas;

    public AudatexEnvios() {}

    public AudatexEnvios(AudatexEnvios value) {
        this.id = value.id;
        this.repuestoId = value.repuestoId;
        this.cotizacionId = value.cotizacionId;
        this.wan = value.wan;
        this.precioOfrecido = value.precioOfrecido;
        this.tiempoEntrega = value.tiempoEntrega;
        this.condicionPieza = value.condicionPieza;
        this.estado = value.estado;
        this.fechaEnvio = value.fechaEnvio;
        this.fechaActualizacion = value.fechaActualizacion;
        this.usuarioEnvio = value.usuarioEnvio;
        this.notas = value.notas;
    }

    public AudatexEnvios(
        Integer id,
        Integer repuestoId,
        String cotizacionId,
        String wan,
        BigDecimal precioOfrecido,
        String tiempoEntrega,
        String condicionPieza,
        AudatexEnviosEstado estado,
        LocalDateTime fechaEnvio,
        LocalDateTime fechaActualizacion,
        String usuarioEnvio,
        String notas
    ) {
        this.id = id;
        this.repuestoId = repuestoId;
        this.cotizacionId = cotizacionId;
        this.wan = wan;
        this.precioOfrecido = precioOfrecido;
        this.tiempoEntrega = tiempoEntrega;
        this.condicionPieza = condicionPieza;
        this.estado = estado;
        this.fechaEnvio = fechaEnvio;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioEnvio = usuarioEnvio;
        this.notas = notas;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.id</code>.
     */
    public AudatexEnvios setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.repuesto_id</code>.
     */
    public Integer getRepuestoId() {
        return this.repuestoId;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.repuesto_id</code>.
     */
    public AudatexEnvios setRepuestoId(Integer repuestoId) {
        this.repuestoId = repuestoId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.cotizacion_id</code>.
     */
    public String getCotizacionId() {
        return this.cotizacionId;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.cotizacion_id</code>.
     */
    public AudatexEnvios setCotizacionId(String cotizacionId) {
        this.cotizacionId = cotizacionId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.wan</code>.
     */
    public String getWan() {
        return this.wan;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.wan</code>.
     */
    public AudatexEnvios setWan(String wan) {
        this.wan = wan;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.precio_ofrecido</code>.
     */
    public BigDecimal getPrecioOfrecido() {
        return this.precioOfrecido;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.precio_ofrecido</code>.
     */
    public AudatexEnvios setPrecioOfrecido(BigDecimal precioOfrecido) {
        this.precioOfrecido = precioOfrecido;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.tiempo_entrega</code>.
     */
    public String getTiempoEntrega() {
        return this.tiempoEntrega;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.tiempo_entrega</code>.
     */
    public AudatexEnvios setTiempoEntrega(String tiempoEntrega) {
        this.tiempoEntrega = tiempoEntrega;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.condicion_pieza</code>.
     */
    public String getCondicionPieza() {
        return this.condicionPieza;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.condicion_pieza</code>.
     */
    public AudatexEnvios setCondicionPieza(String condicionPieza) {
        this.condicionPieza = condicionPieza;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.estado</code>.
     */
    public AudatexEnviosEstado getEstado() {
        return this.estado;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.estado</code>.
     */
    public AudatexEnvios setEstado(AudatexEnviosEstado estado) {
        this.estado = estado;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.fecha_envio</code>.
     */
    public LocalDateTime getFechaEnvio() {
        return this.fechaEnvio;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.fecha_envio</code>.
     */
    public AudatexEnvios setFechaEnvio(LocalDateTime fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.audatex_envios.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.audatex_envios.fecha_actualizacion</code>.
     */
    public AudatexEnvios setFechaActualizacion(LocalDateTime fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.usuario_envio</code>.
     */
    public String getUsuarioEnvio() {
        return this.usuarioEnvio;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.usuario_envio</code>.
     */
    public AudatexEnvios setUsuarioEnvio(String usuarioEnvio) {
        this.usuarioEnvio = usuarioEnvio;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.audatex_envios.notas</code>.
     */
    public String getNotas() {
        return this.notas;
    }

    /**
     * Setter for <code>sistema_vehicular.audatex_envios.notas</code>.
     */
    public AudatexEnvios setNotas(String notas) {
        this.notas = notas;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AudatexEnvios other = (AudatexEnvios) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.repuestoId == null) {
            if (other.repuestoId != null)
                return false;
        }
        else if (!this.repuestoId.equals(other.repuestoId))
            return false;
        if (this.cotizacionId == null) {
            if (other.cotizacionId != null)
                return false;
        }
        else if (!this.cotizacionId.equals(other.cotizacionId))
            return false;
        if (this.wan == null) {
            if (other.wan != null)
                return false;
        }
        else if (!this.wan.equals(other.wan))
            return false;
        if (this.precioOfrecido == null) {
            if (other.precioOfrecido != null)
                return false;
        }
        else if (!this.precioOfrecido.equals(other.precioOfrecido))
            return false;
        if (this.tiempoEntrega == null) {
            if (other.tiempoEntrega != null)
                return false;
        }
        else if (!this.tiempoEntrega.equals(other.tiempoEntrega))
            return false;
        if (this.condicionPieza == null) {
            if (other.condicionPieza != null)
                return false;
        }
        else if (!this.condicionPieza.equals(other.condicionPieza))
            return false;
        if (this.estado == null) {
            if (other.estado != null)
                return false;
        }
        else if (!this.estado.equals(other.estado))
            return false;
        if (this.fechaEnvio == null) {
            if (other.fechaEnvio != null)
                return false;
        }
        else if (!this.fechaEnvio.equals(other.fechaEnvio))
            return false;
        if (this.fechaActualizacion == null) {
            if (other.fechaActualizacion != null)
                return false;
        }
        else if (!this.fechaActualizacion.equals(other.fechaActualizacion))
            return false;
        if (this.usuarioEnvio == null) {
            if (other.usuarioEnvio != null)
                return false;
        }
        else if (!this.usuarioEnvio.equals(other.usuarioEnvio))
            return false;
        if (this.notas == null) {
            if (other.notas != null)
                return false;
        }
        else if (!this.notas.equals(other.notas))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.repuestoId == null) ? 0 : this.repuestoId.hashCode());
        result = prime * result + ((this.cotizacionId == null) ? 0 : this.cotizacionId.hashCode());
        result = prime * result + ((this.wan == null) ? 0 : this.wan.hashCode());
        result = prime * result + ((this.precioOfrecido == null) ? 0 : this.precioOfrecido.hashCode());
        result = prime * result + ((this.tiempoEntrega == null) ? 0 : this.tiempoEntrega.hashCode());
        result = prime * result + ((this.condicionPieza == null) ? 0 : this.condicionPieza.hashCode());
        result = prime * result + ((this.estado == null) ? 0 : this.estado.hashCode());
        result = prime * result + ((this.fechaEnvio == null) ? 0 : this.fechaEnvio.hashCode());
        result = prime * result + ((this.fechaActualizacion == null) ? 0 : this.fechaActualizacion.hashCode());
        result = prime * result + ((this.usuarioEnvio == null) ? 0 : this.usuarioEnvio.hashCode());
        result = prime * result + ((this.notas == null) ? 0 : this.notas.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AudatexEnvios (");

        sb.append(id);
        sb.append(", ").append(repuestoId);
        sb.append(", ").append(cotizacionId);
        sb.append(", ").append(wan);
        sb.append(", ").append(precioOfrecido);
        sb.append(", ").append(tiempoEntrega);
        sb.append(", ").append(condicionPieza);
        sb.append(", ").append(estado);
        sb.append(", ").append(fechaEnvio);
        sb.append(", ").append(fechaActualizacion);
        sb.append(", ").append(usuarioEnvio);
        sb.append(", ").append(notas);

        sb.append(")");
        return sb.toString();
    }
}
