/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import com.rodiejacontable.database.jooq.enums.HistorialVehiculosAccion;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistorialVehiculos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer vehiculoId;
    private HistorialVehiculosAccion accion;
    private String campoModificado;
    private String valorAnterior;
    private String valorNuevo;
    private String usuario;
    private LocalDateTime fechaCambio;
    private String ipUsuario;
    private String observaciones;

    public HistorialVehiculos() {}

    public HistorialVehiculos(HistorialVehiculos value) {
        this.id = value.id;
        this.vehiculoId = value.vehiculoId;
        this.accion = value.accion;
        this.campoModificado = value.campoModificado;
        this.valorAnterior = value.valorAnterior;
        this.valorNuevo = value.valorNuevo;
        this.usuario = value.usuario;
        this.fechaCambio = value.fechaCambio;
        this.ipUsuario = value.ipUsuario;
        this.observaciones = value.observaciones;
    }

    public HistorialVehiculos(
        Integer id,
        Integer vehiculoId,
        HistorialVehiculosAccion accion,
        String campoModificado,
        String valorAnterior,
        String valorNuevo,
        String usuario,
        LocalDateTime fechaCambio,
        String ipUsuario,
        String observaciones
    ) {
        this.id = id;
        this.vehiculoId = vehiculoId;
        this.accion = accion;
        this.campoModificado = campoModificado;
        this.valorAnterior = valorAnterior;
        this.valorNuevo = valorNuevo;
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
        this.ipUsuario = ipUsuario;
        this.observaciones = observaciones;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.id</code>.
     */
    public HistorialVehiculos setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.vehiculo_id</code>.
     */
    public Integer getVehiculoId() {
        return this.vehiculoId;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.vehiculo_id</code>.
     */
    public HistorialVehiculos setVehiculoId(Integer vehiculoId) {
        this.vehiculoId = vehiculoId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.accion</code>.
     */
    public HistorialVehiculosAccion getAccion() {
        return this.accion;
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.accion</code>.
     */
    public HistorialVehiculos setAccion(HistorialVehiculosAccion accion) {
        this.accion = accion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.campo_modificado</code>.
     */
    public String getCampoModificado() {
        return this.campoModificado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.campo_modificado</code>.
     */
    public HistorialVehiculos setCampoModificado(String campoModificado) {
        this.campoModificado = campoModificado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.valor_anterior</code>.
     */
    public String getValorAnterior() {
        return this.valorAnterior;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.valor_anterior</code>.
     */
    public HistorialVehiculos setValorAnterior(String valorAnterior) {
        this.valorAnterior = valorAnterior;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.valor_nuevo</code>.
     */
    public String getValorNuevo() {
        return this.valorNuevo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.valor_nuevo</code>.
     */
    public HistorialVehiculos setValorNuevo(String valorNuevo) {
        this.valorNuevo = valorNuevo;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.usuario</code>.
     */
    public String getUsuario() {
        return this.usuario;
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.usuario</code>.
     */
    public HistorialVehiculos setUsuario(String usuario) {
        this.usuario = usuario;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.fecha_cambio</code>.
     */
    public LocalDateTime getFechaCambio() {
        return this.fechaCambio;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.fecha_cambio</code>.
     */
    public HistorialVehiculos setFechaCambio(LocalDateTime fechaCambio) {
        this.fechaCambio = fechaCambio;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.ip_usuario</code>.
     */
    public String getIpUsuario() {
        return this.ipUsuario;
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.ip_usuario</code>.
     */
    public HistorialVehiculos setIpUsuario(String ipUsuario) {
        this.ipUsuario = ipUsuario;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.observaciones</code>.
     */
    public String getObservaciones() {
        return this.observaciones;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.observaciones</code>.
     */
    public HistorialVehiculos setObservaciones(String observaciones) {
        this.observaciones = observaciones;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final HistorialVehiculos other = (HistorialVehiculos) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.vehiculoId == null) {
            if (other.vehiculoId != null)
                return false;
        }
        else if (!this.vehiculoId.equals(other.vehiculoId))
            return false;
        if (this.accion == null) {
            if (other.accion != null)
                return false;
        }
        else if (!this.accion.equals(other.accion))
            return false;
        if (this.campoModificado == null) {
            if (other.campoModificado != null)
                return false;
        }
        else if (!this.campoModificado.equals(other.campoModificado))
            return false;
        if (this.valorAnterior == null) {
            if (other.valorAnterior != null)
                return false;
        }
        else if (!this.valorAnterior.equals(other.valorAnterior))
            return false;
        if (this.valorNuevo == null) {
            if (other.valorNuevo != null)
                return false;
        }
        else if (!this.valorNuevo.equals(other.valorNuevo))
            return false;
        if (this.usuario == null) {
            if (other.usuario != null)
                return false;
        }
        else if (!this.usuario.equals(other.usuario))
            return false;
        if (this.fechaCambio == null) {
            if (other.fechaCambio != null)
                return false;
        }
        else if (!this.fechaCambio.equals(other.fechaCambio))
            return false;
        if (this.ipUsuario == null) {
            if (other.ipUsuario != null)
                return false;
        }
        else if (!this.ipUsuario.equals(other.ipUsuario))
            return false;
        if (this.observaciones == null) {
            if (other.observaciones != null)
                return false;
        }
        else if (!this.observaciones.equals(other.observaciones))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.vehiculoId == null) ? 0 : this.vehiculoId.hashCode());
        result = prime * result + ((this.accion == null) ? 0 : this.accion.hashCode());
        result = prime * result + ((this.campoModificado == null) ? 0 : this.campoModificado.hashCode());
        result = prime * result + ((this.valorAnterior == null) ? 0 : this.valorAnterior.hashCode());
        result = prime * result + ((this.valorNuevo == null) ? 0 : this.valorNuevo.hashCode());
        result = prime * result + ((this.usuario == null) ? 0 : this.usuario.hashCode());
        result = prime * result + ((this.fechaCambio == null) ? 0 : this.fechaCambio.hashCode());
        result = prime * result + ((this.ipUsuario == null) ? 0 : this.ipUsuario.hashCode());
        result = prime * result + ((this.observaciones == null) ? 0 : this.observaciones.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HistorialVehiculos (");

        sb.append(id);
        sb.append(", ").append(vehiculoId);
        sb.append(", ").append(accion);
        sb.append(", ").append(campoModificado);
        sb.append(", ").append(valorAnterior);
        sb.append(", ").append(valorNuevo);
        sb.append(", ").append(usuario);
        sb.append(", ").append(fechaCambio);
        sb.append(", ").append(ipUsuario);
        sb.append(", ").append(observaciones);

        sb.append(")");
        return sb.toString();
    }
}
