/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Modelos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer marcaId;
    private String nombre;
    private Byte activo;
    private LocalDateTime fechaCreacion;

    public Modelos() {}

    public Modelos(Modelos value) {
        this.id = value.id;
        this.marcaId = value.marcaId;
        this.nombre = value.nombre;
        this.activo = value.activo;
        this.fechaCreacion = value.fechaCreacion;
    }

    public Modelos(
        Integer id,
        Integer marcaId,
        String nombre,
        Byte activo,
        LocalDateTime fechaCreacion
    ) {
        this.id = id;
        this.marcaId = marcaId;
        this.nombre = nombre;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.id</code>.
     */
    public Modelos setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.marca_id</code>.
     */
    public Integer getMarcaId() {
        return this.marcaId;
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.marca_id</code>.
     */
    public Modelos setMarcaId(Integer marcaId) {
        this.marcaId = marcaId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.nombre</code>.
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.nombre</code>.
     */
    public Modelos setNombre(String nombre) {
        this.nombre = nombre;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.activo</code>.
     */
    public Byte getActivo() {
        return this.activo;
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.activo</code>.
     */
    public Modelos setActivo(Byte activo) {
        this.activo = activo;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.fecha_creacion</code>.
     */
    public Modelos setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Modelos other = (Modelos) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.marcaId == null) {
            if (other.marcaId != null)
                return false;
        }
        else if (!this.marcaId.equals(other.marcaId))
            return false;
        if (this.nombre == null) {
            if (other.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(other.nombre))
            return false;
        if (this.activo == null) {
            if (other.activo != null)
                return false;
        }
        else if (!this.activo.equals(other.activo))
            return false;
        if (this.fechaCreacion == null) {
            if (other.fechaCreacion != null)
                return false;
        }
        else if (!this.fechaCreacion.equals(other.fechaCreacion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.marcaId == null) ? 0 : this.marcaId.hashCode());
        result = prime * result + ((this.nombre == null) ? 0 : this.nombre.hashCode());
        result = prime * result + ((this.activo == null) ? 0 : this.activo.hashCode());
        result = prime * result + ((this.fechaCreacion == null) ? 0 : this.fechaCreacion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Modelos (");

        sb.append(id);
        sb.append(", ").append(marcaId);
        sb.append(", ").append(nombre);
        sb.append(", ").append(activo);
        sb.append(", ").append(fechaCreacion);

        sb.append(")");
        return sb.toString();
    }
}
