/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolPermisos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer rolId;
    private Integer submoduloId;
    private Byte canView;
    private Byte canCreate;
    private Byte canEdit;
    private Byte canDelete;

    public RolPermisos() {}

    public RolPermisos(RolPermisos value) {
        this.id = value.id;
        this.rolId = value.rolId;
        this.submoduloId = value.submoduloId;
        this.canView = value.canView;
        this.canCreate = value.canCreate;
        this.canEdit = value.canEdit;
        this.canDelete = value.canDelete;
    }

    public RolPermisos(
        Integer id,
        Integer rolId,
        Integer submoduloId,
        Byte canView,
        Byte canCreate,
        Byte canEdit,
        Byte canDelete
    ) {
        this.id = id;
        this.rolId = rolId;
        this.submoduloId = submoduloId;
        this.canView = canView;
        this.canCreate = canCreate;
        this.canEdit = canEdit;
        this.canDelete = canDelete;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.id</code>.
     */
    public RolPermisos setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.rol_id</code>.
     */
    public Integer getRolId() {
        return this.rolId;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.rol_id</code>.
     */
    public RolPermisos setRolId(Integer rolId) {
        this.rolId = rolId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.submodulo_id</code>.
     */
    public Integer getSubmoduloId() {
        return this.submoduloId;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.submodulo_id</code>.
     */
    public RolPermisos setSubmoduloId(Integer submoduloId) {
        this.submoduloId = submoduloId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.can_view</code>.
     */
    public Byte getCanView() {
        return this.canView;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.can_view</code>.
     */
    public RolPermisos setCanView(Byte canView) {
        this.canView = canView;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.can_create</code>.
     */
    public Byte getCanCreate() {
        return this.canCreate;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.can_create</code>.
     */
    public RolPermisos setCanCreate(Byte canCreate) {
        this.canCreate = canCreate;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.can_edit</code>.
     */
    public Byte getCanEdit() {
        return this.canEdit;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.can_edit</code>.
     */
    public RolPermisos setCanEdit(Byte canEdit) {
        this.canEdit = canEdit;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.rol_permisos.can_delete</code>.
     */
    public Byte getCanDelete() {
        return this.canDelete;
    }

    /**
     * Setter for <code>sistema_vehicular.rol_permisos.can_delete</code>.
     */
    public RolPermisos setCanDelete(Byte canDelete) {
        this.canDelete = canDelete;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RolPermisos other = (RolPermisos) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.rolId == null) {
            if (other.rolId != null)
                return false;
        }
        else if (!this.rolId.equals(other.rolId))
            return false;
        if (this.submoduloId == null) {
            if (other.submoduloId != null)
                return false;
        }
        else if (!this.submoduloId.equals(other.submoduloId))
            return false;
        if (this.canView == null) {
            if (other.canView != null)
                return false;
        }
        else if (!this.canView.equals(other.canView))
            return false;
        if (this.canCreate == null) {
            if (other.canCreate != null)
                return false;
        }
        else if (!this.canCreate.equals(other.canCreate))
            return false;
        if (this.canEdit == null) {
            if (other.canEdit != null)
                return false;
        }
        else if (!this.canEdit.equals(other.canEdit))
            return false;
        if (this.canDelete == null) {
            if (other.canDelete != null)
                return false;
        }
        else if (!this.canDelete.equals(other.canDelete))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.rolId == null) ? 0 : this.rolId.hashCode());
        result = prime * result + ((this.submoduloId == null) ? 0 : this.submoduloId.hashCode());
        result = prime * result + ((this.canView == null) ? 0 : this.canView.hashCode());
        result = prime * result + ((this.canCreate == null) ? 0 : this.canCreate.hashCode());
        result = prime * result + ((this.canEdit == null) ? 0 : this.canEdit.hashCode());
        result = prime * result + ((this.canDelete == null) ? 0 : this.canDelete.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolPermisos (");

        sb.append(id);
        sb.append(", ").append(rolId);
        sb.append(", ").append(submoduloId);
        sb.append(", ").append(canView);
        sb.append(", ").append(canCreate);
        sb.append(", ").append(canEdit);
        sb.append(", ").append(canDelete);

        sb.append(")");
        return sb.toString();
    }
}
