/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Submodulos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer moduloId;
    private String nombre;
    private String clave;

    public Submodulos() {}

    public Submodulos(Submodulos value) {
        this.id = value.id;
        this.moduloId = value.moduloId;
        this.nombre = value.nombre;
        this.clave = value.clave;
    }

    public Submodulos(
        Integer id,
        Integer moduloId,
        String nombre,
        String clave
    ) {
        this.id = id;
        this.moduloId = moduloId;
        this.nombre = nombre;
        this.clave = clave;
    }

    /**
     * Getter for <code>sistema_vehicular.submodulos.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.submodulos.id</code>.
     */
    public Submodulos setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.submodulos.modulo_id</code>.
     */
    public Integer getModuloId() {
        return this.moduloId;
    }

    /**
     * Setter for <code>sistema_vehicular.submodulos.modulo_id</code>.
     */
    public Submodulos setModuloId(Integer moduloId) {
        this.moduloId = moduloId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.submodulos.nombre</code>.
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>sistema_vehicular.submodulos.nombre</code>.
     */
    public Submodulos setNombre(String nombre) {
        this.nombre = nombre;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.submodulos.clave</code>.
     */
    public String getClave() {
        return this.clave;
    }

    /**
     * Setter for <code>sistema_vehicular.submodulos.clave</code>.
     */
    public Submodulos setClave(String clave) {
        this.clave = clave;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Submodulos other = (Submodulos) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.moduloId == null) {
            if (other.moduloId != null)
                return false;
        }
        else if (!this.moduloId.equals(other.moduloId))
            return false;
        if (this.nombre == null) {
            if (other.nombre != null)
                return false;
        }
        else if (!this.nombre.equals(other.nombre))
            return false;
        if (this.clave == null) {
            if (other.clave != null)
                return false;
        }
        else if (!this.clave.equals(other.clave))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.moduloId == null) ? 0 : this.moduloId.hashCode());
        result = prime * result + ((this.nombre == null) ? 0 : this.nombre.hashCode());
        result = prime * result + ((this.clave == null) ? 0 : this.clave.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Submodulos (");

        sb.append(id);
        sb.append(", ").append(moduloId);
        sb.append(", ").append(nombre);
        sb.append(", ").append(clave);

        sb.append(")");
        return sb.toString();
    }
}
