/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import com.rodiejacontable.database.jooq.enums.VehiculosCombustible;
import com.rodiejacontable.database.jooq.enums.VehiculosEstado;
import com.rodiejacontable.database.jooq.enums.VehiculosTraccion;
import com.rodiejacontable.database.jooq.enums.VehiculosTransmision;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vehiculos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String codigoVehiculo;
    private Integer generacionId;
    private String imagenUrl;
    private Integer anio;
    private BigDecimal precioCompra;
    private BigDecimal costoGrua;
    private BigDecimal comisiones;
    private BigDecimal inversionTotal;
    private BigDecimal costoRecuperado;
    private BigDecimal costoPendiente;
    private VehiculosTraccion traccion;
    private VehiculosTransmision transmision;
    private VehiculosCombustible combustible;
    private String cilindraje;
    private LocalDate fechaIngreso;
    private VehiculosEstado estado;
    private BigDecimal precioVenta;
    private LocalDate fechaVenta;
    private Byte activo;
    private String notas;
    private LocalDateTime fechaCreacion;
    private LocalDateTime fechaActualizacion;

    public Vehiculos() {}

    public Vehiculos(Vehiculos value) {
        this.id = value.id;
        this.codigoVehiculo = value.codigoVehiculo;
        this.generacionId = value.generacionId;
        this.imagenUrl = value.imagenUrl;
        this.anio = value.anio;
        this.precioCompra = value.precioCompra;
        this.costoGrua = value.costoGrua;
        this.comisiones = value.comisiones;
        this.inversionTotal = value.inversionTotal;
        this.costoRecuperado = value.costoRecuperado;
        this.costoPendiente = value.costoPendiente;
        this.traccion = value.traccion;
        this.transmision = value.transmision;
        this.combustible = value.combustible;
        this.cilindraje = value.cilindraje;
        this.fechaIngreso = value.fechaIngreso;
        this.estado = value.estado;
        this.precioVenta = value.precioVenta;
        this.fechaVenta = value.fechaVenta;
        this.activo = value.activo;
        this.notas = value.notas;
        this.fechaCreacion = value.fechaCreacion;
        this.fechaActualizacion = value.fechaActualizacion;
    }

    public Vehiculos(
        Integer id,
        String codigoVehiculo,
        Integer generacionId,
        String imagenUrl,
        Integer anio,
        BigDecimal precioCompra,
        BigDecimal costoGrua,
        BigDecimal comisiones,
        BigDecimal inversionTotal,
        BigDecimal costoRecuperado,
        BigDecimal costoPendiente,
        VehiculosTraccion traccion,
        VehiculosTransmision transmision,
        VehiculosCombustible combustible,
        String cilindraje,
        LocalDate fechaIngreso,
        VehiculosEstado estado,
        BigDecimal precioVenta,
        LocalDate fechaVenta,
        Byte activo,
        String notas,
        LocalDateTime fechaCreacion,
        LocalDateTime fechaActualizacion
    ) {
        this.id = id;
        this.codigoVehiculo = codigoVehiculo;
        this.generacionId = generacionId;
        this.imagenUrl = imagenUrl;
        this.anio = anio;
        this.precioCompra = precioCompra;
        this.costoGrua = costoGrua;
        this.comisiones = comisiones;
        this.inversionTotal = inversionTotal;
        this.costoRecuperado = costoRecuperado;
        this.costoPendiente = costoPendiente;
        this.traccion = traccion;
        this.transmision = transmision;
        this.combustible = combustible;
        this.cilindraje = cilindraje;
        this.fechaIngreso = fechaIngreso;
        this.estado = estado;
        this.precioVenta = precioVenta;
        this.fechaVenta = fechaVenta;
        this.activo = activo;
        this.notas = notas;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.id</code>.
     */
    public Vehiculos setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return this.codigoVehiculo;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.codigo_vehiculo</code>.
     */
    public Vehiculos setCodigoVehiculo(String codigoVehiculo) {
        this.codigoVehiculo = codigoVehiculo;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return this.generacionId;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.generacion_id</code>.
     */
    public Vehiculos setGeneracionId(Integer generacionId) {
        this.generacionId = generacionId;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.imagen_url</code>.
     */
    public String getImagenUrl() {
        return this.imagenUrl;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.imagen_url</code>.
     */
    public Vehiculos setImagenUrl(String imagenUrl) {
        this.imagenUrl = imagenUrl;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.anio</code>.
     */
    public Integer getAnio() {
        return this.anio;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.anio</code>.
     */
    public Vehiculos setAnio(Integer anio) {
        this.anio = anio;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.precio_compra</code>.
     */
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.precio_compra</code>.
     */
    public Vehiculos setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_grua</code>.
     */
    public BigDecimal getCostoGrua() {
        return this.costoGrua;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_grua</code>.
     */
    public Vehiculos setCostoGrua(BigDecimal costoGrua) {
        this.costoGrua = costoGrua;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.comisiones</code>.
     */
    public BigDecimal getComisiones() {
        return this.comisiones;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.comisiones</code>.
     */
    public Vehiculos setComisiones(BigDecimal comisiones) {
        this.comisiones = comisiones;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.inversion_total</code>.
     */
    public BigDecimal getInversionTotal() {
        return this.inversionTotal;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.inversion_total</code>.
     */
    public Vehiculos setInversionTotal(BigDecimal inversionTotal) {
        this.inversionTotal = inversionTotal;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_recuperado</code>.
     */
    public BigDecimal getCostoRecuperado() {
        return this.costoRecuperado;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_recuperado</code>.
     */
    public Vehiculos setCostoRecuperado(BigDecimal costoRecuperado) {
        this.costoRecuperado = costoRecuperado;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_pendiente</code>.
     */
    public BigDecimal getCostoPendiente() {
        return this.costoPendiente;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_pendiente</code>.
     */
    public Vehiculos setCostoPendiente(BigDecimal costoPendiente) {
        this.costoPendiente = costoPendiente;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.traccion</code>.
     */
    public VehiculosTraccion getTraccion() {
        return this.traccion;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.traccion</code>.
     */
    public Vehiculos setTraccion(VehiculosTraccion traccion) {
        this.traccion = traccion;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.transmision</code>.
     */
    public VehiculosTransmision getTransmision() {
        return this.transmision;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.transmision</code>.
     */
    public Vehiculos setTransmision(VehiculosTransmision transmision) {
        this.transmision = transmision;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.combustible</code>.
     */
    public VehiculosCombustible getCombustible() {
        return this.combustible;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.combustible</code>.
     */
    public Vehiculos setCombustible(VehiculosCombustible combustible) {
        this.combustible = combustible;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.cilindraje</code>.
     */
    public String getCilindraje() {
        return this.cilindraje;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.cilindraje</code>.
     */
    public Vehiculos setCilindraje(String cilindraje) {
        this.cilindraje = cilindraje;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_ingreso</code>.
     */
    public LocalDate getFechaIngreso() {
        return this.fechaIngreso;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_ingreso</code>.
     */
    public Vehiculos setFechaIngreso(LocalDate fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.estado</code>.
     */
    public VehiculosEstado getEstado() {
        return this.estado;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.estado</code>.
     */
    public Vehiculos setEstado(VehiculosEstado estado) {
        this.estado = estado;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.precio_venta</code>.
     */
    public Vehiculos setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_venta</code>.
     */
    public LocalDate getFechaVenta() {
        return this.fechaVenta;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_venta</code>.
     */
    public Vehiculos setFechaVenta(LocalDate fechaVenta) {
        this.fechaVenta = fechaVenta;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.activo</code>.
     */
    public Byte getActivo() {
        return this.activo;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.activo</code>.
     */
    public Vehiculos setActivo(Byte activo) {
        this.activo = activo;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.notas</code>.
     */
    public String getNotas() {
        return this.notas;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.notas</code>.
     */
    public Vehiculos setNotas(String notas) {
        this.notas = notas;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_creacion</code>.
     */
    public Vehiculos setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_actualizacion</code>.
     */
    public Vehiculos setFechaActualizacion(LocalDateTime fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Vehiculos other = (Vehiculos) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.codigoVehiculo == null) {
            if (other.codigoVehiculo != null)
                return false;
        }
        else if (!this.codigoVehiculo.equals(other.codigoVehiculo))
            return false;
        if (this.generacionId == null) {
            if (other.generacionId != null)
                return false;
        }
        else if (!this.generacionId.equals(other.generacionId))
            return false;
        if (this.imagenUrl == null) {
            if (other.imagenUrl != null)
                return false;
        }
        else if (!this.imagenUrl.equals(other.imagenUrl))
            return false;
        if (this.anio == null) {
            if (other.anio != null)
                return false;
        }
        else if (!this.anio.equals(other.anio))
            return false;
        if (this.precioCompra == null) {
            if (other.precioCompra != null)
                return false;
        }
        else if (!this.precioCompra.equals(other.precioCompra))
            return false;
        if (this.costoGrua == null) {
            if (other.costoGrua != null)
                return false;
        }
        else if (!this.costoGrua.equals(other.costoGrua))
            return false;
        if (this.comisiones == null) {
            if (other.comisiones != null)
                return false;
        }
        else if (!this.comisiones.equals(other.comisiones))
            return false;
        if (this.inversionTotal == null) {
            if (other.inversionTotal != null)
                return false;
        }
        else if (!this.inversionTotal.equals(other.inversionTotal))
            return false;
        if (this.costoRecuperado == null) {
            if (other.costoRecuperado != null)
                return false;
        }
        else if (!this.costoRecuperado.equals(other.costoRecuperado))
            return false;
        if (this.costoPendiente == null) {
            if (other.costoPendiente != null)
                return false;
        }
        else if (!this.costoPendiente.equals(other.costoPendiente))
            return false;
        if (this.traccion == null) {
            if (other.traccion != null)
                return false;
        }
        else if (!this.traccion.equals(other.traccion))
            return false;
        if (this.transmision == null) {
            if (other.transmision != null)
                return false;
        }
        else if (!this.transmision.equals(other.transmision))
            return false;
        if (this.combustible == null) {
            if (other.combustible != null)
                return false;
        }
        else if (!this.combustible.equals(other.combustible))
            return false;
        if (this.cilindraje == null) {
            if (other.cilindraje != null)
                return false;
        }
        else if (!this.cilindraje.equals(other.cilindraje))
            return false;
        if (this.fechaIngreso == null) {
            if (other.fechaIngreso != null)
                return false;
        }
        else if (!this.fechaIngreso.equals(other.fechaIngreso))
            return false;
        if (this.estado == null) {
            if (other.estado != null)
                return false;
        }
        else if (!this.estado.equals(other.estado))
            return false;
        if (this.precioVenta == null) {
            if (other.precioVenta != null)
                return false;
        }
        else if (!this.precioVenta.equals(other.precioVenta))
            return false;
        if (this.fechaVenta == null) {
            if (other.fechaVenta != null)
                return false;
        }
        else if (!this.fechaVenta.equals(other.fechaVenta))
            return false;
        if (this.activo == null) {
            if (other.activo != null)
                return false;
        }
        else if (!this.activo.equals(other.activo))
            return false;
        if (this.notas == null) {
            if (other.notas != null)
                return false;
        }
        else if (!this.notas.equals(other.notas))
            return false;
        if (this.fechaCreacion == null) {
            if (other.fechaCreacion != null)
                return false;
        }
        else if (!this.fechaCreacion.equals(other.fechaCreacion))
            return false;
        if (this.fechaActualizacion == null) {
            if (other.fechaActualizacion != null)
                return false;
        }
        else if (!this.fechaActualizacion.equals(other.fechaActualizacion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.codigoVehiculo == null) ? 0 : this.codigoVehiculo.hashCode());
        result = prime * result + ((this.generacionId == null) ? 0 : this.generacionId.hashCode());
        result = prime * result + ((this.imagenUrl == null) ? 0 : this.imagenUrl.hashCode());
        result = prime * result + ((this.anio == null) ? 0 : this.anio.hashCode());
        result = prime * result + ((this.precioCompra == null) ? 0 : this.precioCompra.hashCode());
        result = prime * result + ((this.costoGrua == null) ? 0 : this.costoGrua.hashCode());
        result = prime * result + ((this.comisiones == null) ? 0 : this.comisiones.hashCode());
        result = prime * result + ((this.inversionTotal == null) ? 0 : this.inversionTotal.hashCode());
        result = prime * result + ((this.costoRecuperado == null) ? 0 : this.costoRecuperado.hashCode());
        result = prime * result + ((this.costoPendiente == null) ? 0 : this.costoPendiente.hashCode());
        result = prime * result + ((this.traccion == null) ? 0 : this.traccion.hashCode());
        result = prime * result + ((this.transmision == null) ? 0 : this.transmision.hashCode());
        result = prime * result + ((this.combustible == null) ? 0 : this.combustible.hashCode());
        result = prime * result + ((this.cilindraje == null) ? 0 : this.cilindraje.hashCode());
        result = prime * result + ((this.fechaIngreso == null) ? 0 : this.fechaIngreso.hashCode());
        result = prime * result + ((this.estado == null) ? 0 : this.estado.hashCode());
        result = prime * result + ((this.precioVenta == null) ? 0 : this.precioVenta.hashCode());
        result = prime * result + ((this.fechaVenta == null) ? 0 : this.fechaVenta.hashCode());
        result = prime * result + ((this.activo == null) ? 0 : this.activo.hashCode());
        result = prime * result + ((this.notas == null) ? 0 : this.notas.hashCode());
        result = prime * result + ((this.fechaCreacion == null) ? 0 : this.fechaCreacion.hashCode());
        result = prime * result + ((this.fechaActualizacion == null) ? 0 : this.fechaActualizacion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vehiculos (");

        sb.append(id);
        sb.append(", ").append(codigoVehiculo);
        sb.append(", ").append(generacionId);
        sb.append(", ").append(imagenUrl);
        sb.append(", ").append(anio);
        sb.append(", ").append(precioCompra);
        sb.append(", ").append(costoGrua);
        sb.append(", ").append(comisiones);
        sb.append(", ").append(inversionTotal);
        sb.append(", ").append(costoRecuperado);
        sb.append(", ").append(costoPendiente);
        sb.append(", ").append(traccion);
        sb.append(", ").append(transmision);
        sb.append(", ").append(combustible);
        sb.append(", ").append(cilindraje);
        sb.append(", ").append(fechaIngreso);
        sb.append(", ").append(estado);
        sb.append(", ").append(precioVenta);
        sb.append(", ").append(fechaVenta);
        sb.append(", ").append(activo);
        sb.append(", ").append(notas);
        sb.append(", ").append(fechaCreacion);
        sb.append(", ").append(fechaActualizacion);

        sb.append(")");
        return sb.toString();
    }
}
