/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import com.rodiejacontable.database.jooq.enums.VistaTransaccionesCompletasCategoria;
import com.rodiejacontable.database.jooq.enums.VistaTransaccionesCompletasEstado;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaTransaccionesCompletas implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String codigoTransaccion;
    private LocalDate fecha;
    private BigDecimal monto;
    private BigDecimal comisionEmpleado;
    private String descripcion;
    private String referencia;
    private VistaTransaccionesCompletasEstado estado;
    private String tipoTransaccion;
    private VistaTransaccionesCompletasCategoria categoria;
    private String empleado;
    private String codigoVehiculo;
    private String codigoRepuesto;
    private String marca;
    private String modelo;
    private String generacion;
    private String claveGeneracion;

    public VistaTransaccionesCompletas() {}

    public VistaTransaccionesCompletas(VistaTransaccionesCompletas value) {
        this.id = value.id;
        this.codigoTransaccion = value.codigoTransaccion;
        this.fecha = value.fecha;
        this.monto = value.monto;
        this.comisionEmpleado = value.comisionEmpleado;
        this.descripcion = value.descripcion;
        this.referencia = value.referencia;
        this.estado = value.estado;
        this.tipoTransaccion = value.tipoTransaccion;
        this.categoria = value.categoria;
        this.empleado = value.empleado;
        this.codigoVehiculo = value.codigoVehiculo;
        this.codigoRepuesto = value.codigoRepuesto;
        this.marca = value.marca;
        this.modelo = value.modelo;
        this.generacion = value.generacion;
        this.claveGeneracion = value.claveGeneracion;
    }

    public VistaTransaccionesCompletas(
        Integer id,
        String codigoTransaccion,
        LocalDate fecha,
        BigDecimal monto,
        BigDecimal comisionEmpleado,
        String descripcion,
        String referencia,
        VistaTransaccionesCompletasEstado estado,
        String tipoTransaccion,
        VistaTransaccionesCompletasCategoria categoria,
        String empleado,
        String codigoVehiculo,
        String codigoRepuesto,
        String marca,
        String modelo,
        String generacion,
        String claveGeneracion
    ) {
        this.id = id;
        this.codigoTransaccion = codigoTransaccion;
        this.fecha = fecha;
        this.monto = monto;
        this.comisionEmpleado = comisionEmpleado;
        this.descripcion = descripcion;
        this.referencia = referencia;
        this.estado = estado;
        this.tipoTransaccion = tipoTransaccion;
        this.categoria = categoria;
        this.empleado = empleado;
        this.codigoVehiculo = codigoVehiculo;
        this.codigoRepuesto = codigoRepuesto;
        this.marca = marca;
        this.modelo = modelo;
        this.generacion = generacion;
        this.claveGeneracion = claveGeneracion;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.id</code>.
     */
    public VistaTransaccionesCompletas setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_transaccion</code>.
     */
    public String getCodigoTransaccion() {
        return this.codigoTransaccion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_transaccion</code>.
     */
    public VistaTransaccionesCompletas setCodigoTransaccion(String codigoTransaccion) {
        this.codigoTransaccion = codigoTransaccion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.fecha</code>.
     */
    public LocalDate getFecha() {
        return this.fecha;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.fecha</code>.
     */
    public VistaTransaccionesCompletas setFecha(LocalDate fecha) {
        this.fecha = fecha;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.monto</code>.
     */
    public BigDecimal getMonto() {
        return this.monto;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.monto</code>.
     */
    public VistaTransaccionesCompletas setMonto(BigDecimal monto) {
        this.monto = monto;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.comision_empleado</code>.
     */
    public BigDecimal getComisionEmpleado() {
        return this.comisionEmpleado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.comision_empleado</code>.
     */
    public VistaTransaccionesCompletas setComisionEmpleado(BigDecimal comisionEmpleado) {
        this.comisionEmpleado = comisionEmpleado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.descripcion</code>.
     */
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.descripcion</code>.
     */
    public VistaTransaccionesCompletas setDescripcion(String descripcion) {
        this.descripcion = descripcion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.referencia</code>.
     */
    public String getReferencia() {
        return this.referencia;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.referencia</code>.
     */
    public VistaTransaccionesCompletas setReferencia(String referencia) {
        this.referencia = referencia;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.estado</code>.
     */
    public VistaTransaccionesCompletasEstado getEstado() {
        return this.estado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.estado</code>.
     */
    public VistaTransaccionesCompletas setEstado(VistaTransaccionesCompletasEstado estado) {
        this.estado = estado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.tipo_transaccion</code>.
     */
    public String getTipoTransaccion() {
        return this.tipoTransaccion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.tipo_transaccion</code>.
     */
    public VistaTransaccionesCompletas setTipoTransaccion(String tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.categoria</code>.
     */
    public VistaTransaccionesCompletasCategoria getCategoria() {
        return this.categoria;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.categoria</code>.
     */
    public VistaTransaccionesCompletas setCategoria(VistaTransaccionesCompletasCategoria categoria) {
        this.categoria = categoria;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.empleado</code>.
     */
    public String getEmpleado() {
        return this.empleado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.empleado</code>.
     */
    public VistaTransaccionesCompletas setEmpleado(String empleado) {
        this.empleado = empleado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return this.codigoVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_vehiculo</code>.
     */
    public VistaTransaccionesCompletas setCodigoVehiculo(String codigoVehiculo) {
        this.codigoVehiculo = codigoVehiculo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_repuesto</code>.
     */
    public String getCodigoRepuesto() {
        return this.codigoRepuesto;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_repuesto</code>.
     */
    public VistaTransaccionesCompletas setCodigoRepuesto(String codigoRepuesto) {
        this.codigoRepuesto = codigoRepuesto;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.marca</code>.
     */
    public String getMarca() {
        return this.marca;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.marca</code>.
     */
    public VistaTransaccionesCompletas setMarca(String marca) {
        this.marca = marca;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.modelo</code>.
     */
    public String getModelo() {
        return this.modelo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.modelo</code>.
     */
    public VistaTransaccionesCompletas setModelo(String modelo) {
        this.modelo = modelo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.generacion</code>.
     */
    public String getGeneracion() {
        return this.generacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.generacion</code>.
     */
    public VistaTransaccionesCompletas setGeneracion(String generacion) {
        this.generacion = generacion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return this.claveGeneracion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.clave_generacion</code>.
     */
    public VistaTransaccionesCompletas setClaveGeneracion(String claveGeneracion) {
        this.claveGeneracion = claveGeneracion;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaTransaccionesCompletas other = (VistaTransaccionesCompletas) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.codigoTransaccion == null) {
            if (other.codigoTransaccion != null)
                return false;
        }
        else if (!this.codigoTransaccion.equals(other.codigoTransaccion))
            return false;
        if (this.fecha == null) {
            if (other.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(other.fecha))
            return false;
        if (this.monto == null) {
            if (other.monto != null)
                return false;
        }
        else if (!this.monto.equals(other.monto))
            return false;
        if (this.comisionEmpleado == null) {
            if (other.comisionEmpleado != null)
                return false;
        }
        else if (!this.comisionEmpleado.equals(other.comisionEmpleado))
            return false;
        if (this.descripcion == null) {
            if (other.descripcion != null)
                return false;
        }
        else if (!this.descripcion.equals(other.descripcion))
            return false;
        if (this.referencia == null) {
            if (other.referencia != null)
                return false;
        }
        else if (!this.referencia.equals(other.referencia))
            return false;
        if (this.estado == null) {
            if (other.estado != null)
                return false;
        }
        else if (!this.estado.equals(other.estado))
            return false;
        if (this.tipoTransaccion == null) {
            if (other.tipoTransaccion != null)
                return false;
        }
        else if (!this.tipoTransaccion.equals(other.tipoTransaccion))
            return false;
        if (this.categoria == null) {
            if (other.categoria != null)
                return false;
        }
        else if (!this.categoria.equals(other.categoria))
            return false;
        if (this.empleado == null) {
            if (other.empleado != null)
                return false;
        }
        else if (!this.empleado.equals(other.empleado))
            return false;
        if (this.codigoVehiculo == null) {
            if (other.codigoVehiculo != null)
                return false;
        }
        else if (!this.codigoVehiculo.equals(other.codigoVehiculo))
            return false;
        if (this.codigoRepuesto == null) {
            if (other.codigoRepuesto != null)
                return false;
        }
        else if (!this.codigoRepuesto.equals(other.codigoRepuesto))
            return false;
        if (this.marca == null) {
            if (other.marca != null)
                return false;
        }
        else if (!this.marca.equals(other.marca))
            return false;
        if (this.modelo == null) {
            if (other.modelo != null)
                return false;
        }
        else if (!this.modelo.equals(other.modelo))
            return false;
        if (this.generacion == null) {
            if (other.generacion != null)
                return false;
        }
        else if (!this.generacion.equals(other.generacion))
            return false;
        if (this.claveGeneracion == null) {
            if (other.claveGeneracion != null)
                return false;
        }
        else if (!this.claveGeneracion.equals(other.claveGeneracion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.codigoTransaccion == null) ? 0 : this.codigoTransaccion.hashCode());
        result = prime * result + ((this.fecha == null) ? 0 : this.fecha.hashCode());
        result = prime * result + ((this.monto == null) ? 0 : this.monto.hashCode());
        result = prime * result + ((this.comisionEmpleado == null) ? 0 : this.comisionEmpleado.hashCode());
        result = prime * result + ((this.descripcion == null) ? 0 : this.descripcion.hashCode());
        result = prime * result + ((this.referencia == null) ? 0 : this.referencia.hashCode());
        result = prime * result + ((this.estado == null) ? 0 : this.estado.hashCode());
        result = prime * result + ((this.tipoTransaccion == null) ? 0 : this.tipoTransaccion.hashCode());
        result = prime * result + ((this.categoria == null) ? 0 : this.categoria.hashCode());
        result = prime * result + ((this.empleado == null) ? 0 : this.empleado.hashCode());
        result = prime * result + ((this.codigoVehiculo == null) ? 0 : this.codigoVehiculo.hashCode());
        result = prime * result + ((this.codigoRepuesto == null) ? 0 : this.codigoRepuesto.hashCode());
        result = prime * result + ((this.marca == null) ? 0 : this.marca.hashCode());
        result = prime * result + ((this.modelo == null) ? 0 : this.modelo.hashCode());
        result = prime * result + ((this.generacion == null) ? 0 : this.generacion.hashCode());
        result = prime * result + ((this.claveGeneracion == null) ? 0 : this.claveGeneracion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaTransaccionesCompletas (");

        sb.append(id);
        sb.append(", ").append(codigoTransaccion);
        sb.append(", ").append(fecha);
        sb.append(", ").append(monto);
        sb.append(", ").append(comisionEmpleado);
        sb.append(", ").append(descripcion);
        sb.append(", ").append(referencia);
        sb.append(", ").append(estado);
        sb.append(", ").append(tipoTransaccion);
        sb.append(", ").append(categoria);
        sb.append(", ").append(empleado);
        sb.append(", ").append(codigoVehiculo);
        sb.append(", ").append(codigoRepuesto);
        sb.append(", ").append(marca);
        sb.append(", ").append(modelo);
        sb.append(", ").append(generacion);
        sb.append(", ").append(claveGeneracion);

        sb.append(")");
        return sb.toString();
    }
}
