/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoBodega;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoCarton;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoCondicion;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoEstado;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoEstante;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoHorizontal;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoMalla;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoNivel;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoPared;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoPiso;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoPlastica;
import com.rodiejacontable.database.jooq.enums.VistaInventarioCompletoZona;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VistaInventarioCompleto implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String codigoRepuesto;
    private String codigoUbicacion;
    private String imagenUrl;
    private Integer parteVehiculoId;
    private String parteVehiculo;
    private String descripcion;
    private BigDecimal precioCosto;
    private BigDecimal precioVenta;
    private BigDecimal precioMayoreo;
    private BigDecimal formula_15;
    private BigDecimal formula_30;
    private VistaInventarioCompletoBodega bodega;
    private VistaInventarioCompletoZona zona;
    private VistaInventarioCompletoPared pared;
    private VistaInventarioCompletoMalla malla;
    private VistaInventarioCompletoHorizontal horizontal;
    private VistaInventarioCompletoEstante estante;
    private VistaInventarioCompletoNivel nivel;
    private VistaInventarioCompletoPiso piso;
    private VistaInventarioCompletoPlastica plastica;
    private VistaInventarioCompletoCarton carton;
    private String posicion;
    private UInteger cantidad;
    private VistaInventarioCompletoEstado estado;
    private VistaInventarioCompletoCondicion condicion;
    private Short anioRegistro;
    private Byte mesRegistro;
    private LocalDateTime fechaCreacion;
    private LocalDateTime fechaActualizacion;
    private Byte activo;
    private String codigoVehiculo;
    private String marca;
    private String modelo;
    private String generacion;
    private Integer anioVehiculo;
    private String claveGeneracion;

    public VistaInventarioCompleto() {}

    public VistaInventarioCompleto(VistaInventarioCompleto value) {
        this.id = value.id;
        this.codigoRepuesto = value.codigoRepuesto;
        this.codigoUbicacion = value.codigoUbicacion;
        this.imagenUrl = value.imagenUrl;
        this.parteVehiculoId = value.parteVehiculoId;
        this.parteVehiculo = value.parteVehiculo;
        this.descripcion = value.descripcion;
        this.precioCosto = value.precioCosto;
        this.precioVenta = value.precioVenta;
        this.precioMayoreo = value.precioMayoreo;
        this.formula_15 = value.formula_15;
        this.formula_30 = value.formula_30;
        this.bodega = value.bodega;
        this.zona = value.zona;
        this.pared = value.pared;
        this.malla = value.malla;
        this.horizontal = value.horizontal;
        this.estante = value.estante;
        this.nivel = value.nivel;
        this.piso = value.piso;
        this.plastica = value.plastica;
        this.carton = value.carton;
        this.posicion = value.posicion;
        this.cantidad = value.cantidad;
        this.estado = value.estado;
        this.condicion = value.condicion;
        this.anioRegistro = value.anioRegistro;
        this.mesRegistro = value.mesRegistro;
        this.fechaCreacion = value.fechaCreacion;
        this.fechaActualizacion = value.fechaActualizacion;
        this.activo = value.activo;
        this.codigoVehiculo = value.codigoVehiculo;
        this.marca = value.marca;
        this.modelo = value.modelo;
        this.generacion = value.generacion;
        this.anioVehiculo = value.anioVehiculo;
        this.claveGeneracion = value.claveGeneracion;
    }

    public VistaInventarioCompleto(
        Integer id,
        String codigoRepuesto,
        String codigoUbicacion,
        String imagenUrl,
        Integer parteVehiculoId,
        String parteVehiculo,
        String descripcion,
        BigDecimal precioCosto,
        BigDecimal precioVenta,
        BigDecimal precioMayoreo,
        BigDecimal formula_15,
        BigDecimal formula_30,
        VistaInventarioCompletoBodega bodega,
        VistaInventarioCompletoZona zona,
        VistaInventarioCompletoPared pared,
        VistaInventarioCompletoMalla malla,
        VistaInventarioCompletoHorizontal horizontal,
        VistaInventarioCompletoEstante estante,
        VistaInventarioCompletoNivel nivel,
        VistaInventarioCompletoPiso piso,
        VistaInventarioCompletoPlastica plastica,
        VistaInventarioCompletoCarton carton,
        String posicion,
        UInteger cantidad,
        VistaInventarioCompletoEstado estado,
        VistaInventarioCompletoCondicion condicion,
        Short anioRegistro,
        Byte mesRegistro,
        LocalDateTime fechaCreacion,
        LocalDateTime fechaActualizacion,
        Byte activo,
        String codigoVehiculo,
        String marca,
        String modelo,
        String generacion,
        Integer anioVehiculo,
        String claveGeneracion
    ) {
        this.id = id;
        this.codigoRepuesto = codigoRepuesto;
        this.codigoUbicacion = codigoUbicacion;
        this.imagenUrl = imagenUrl;
        this.parteVehiculoId = parteVehiculoId;
        this.parteVehiculo = parteVehiculo;
        this.descripcion = descripcion;
        this.precioCosto = precioCosto;
        this.precioVenta = precioVenta;
        this.precioMayoreo = precioMayoreo;
        this.formula_15 = formula_15;
        this.formula_30 = formula_30;
        this.bodega = bodega;
        this.zona = zona;
        this.pared = pared;
        this.malla = malla;
        this.horizontal = horizontal;
        this.estante = estante;
        this.nivel = nivel;
        this.piso = piso;
        this.plastica = plastica;
        this.carton = carton;
        this.posicion = posicion;
        this.cantidad = cantidad;
        this.estado = estado;
        this.condicion = condicion;
        this.anioRegistro = anioRegistro;
        this.mesRegistro = mesRegistro;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
        this.activo = activo;
        this.codigoVehiculo = codigoVehiculo;
        this.marca = marca;
        this.modelo = modelo;
        this.generacion = generacion;
        this.anioVehiculo = anioVehiculo;
        this.claveGeneracion = claveGeneracion;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_inventario_completo.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_inventario_completo.id</code>.
     */
    public VistaInventarioCompleto setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.codigo_repuesto</code>.
     */
    public String getCodigoRepuesto() {
        return this.codigoRepuesto;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.codigo_repuesto</code>.
     */
    public VistaInventarioCompleto setCodigoRepuesto(String codigoRepuesto) {
        this.codigoRepuesto = codigoRepuesto;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.codigo_ubicacion</code>.
     */
    public String getCodigoUbicacion() {
        return this.codigoUbicacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.codigo_ubicacion</code>.
     */
    public VistaInventarioCompleto setCodigoUbicacion(String codigoUbicacion) {
        this.codigoUbicacion = codigoUbicacion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.imagen_url</code>.
     */
    public String getImagenUrl() {
        return this.imagenUrl;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.imagen_url</code>.
     */
    public VistaInventarioCompleto setImagenUrl(String imagenUrl) {
        this.imagenUrl = imagenUrl;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.parte_vehiculo_id</code>.
     */
    public Integer getParteVehiculoId() {
        return this.parteVehiculoId;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.parte_vehiculo_id</code>.
     */
    public VistaInventarioCompleto setParteVehiculoId(Integer parteVehiculoId) {
        this.parteVehiculoId = parteVehiculoId;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.parte_vehiculo</code>.
     */
    public String getParteVehiculo() {
        return this.parteVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.parte_vehiculo</code>.
     */
    public VistaInventarioCompleto setParteVehiculo(String parteVehiculo) {
        this.parteVehiculo = parteVehiculo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.descripcion</code>.
     */
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.descripcion</code>.
     */
    public VistaInventarioCompleto setDescripcion(String descripcion) {
        this.descripcion = descripcion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.precio_costo</code>.
     */
    public BigDecimal getPrecioCosto() {
        return this.precioCosto;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.precio_costo</code>.
     */
    public VistaInventarioCompleto setPrecioCosto(BigDecimal precioCosto) {
        this.precioCosto = precioCosto;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.precio_venta</code>.
     */
    public VistaInventarioCompleto setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.precio_mayoreo</code>.
     */
    public BigDecimal getPrecioMayoreo() {
        return this.precioMayoreo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.precio_mayoreo</code>.
     */
    public VistaInventarioCompleto setPrecioMayoreo(BigDecimal precioMayoreo) {
        this.precioMayoreo = precioMayoreo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.formula_15</code>.
     */
    public BigDecimal getFormula_15() {
        return this.formula_15;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.formula_15</code>.
     */
    public VistaInventarioCompleto setFormula_15(BigDecimal formula_15) {
        this.formula_15 = formula_15;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.formula_30</code>.
     */
    public BigDecimal getFormula_30() {
        return this.formula_30;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.formula_30</code>.
     */
    public VistaInventarioCompleto setFormula_30(BigDecimal formula_30) {
        this.formula_30 = formula_30;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.bodega</code>.
     */
    public VistaInventarioCompletoBodega getBodega() {
        return this.bodega;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.bodega</code>.
     */
    public VistaInventarioCompleto setBodega(VistaInventarioCompletoBodega bodega) {
        this.bodega = bodega;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_inventario_completo.zona</code>.
     */
    public VistaInventarioCompletoZona getZona() {
        return this.zona;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_inventario_completo.zona</code>.
     */
    public VistaInventarioCompleto setZona(VistaInventarioCompletoZona zona) {
        this.zona = zona;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.pared</code>.
     */
    public VistaInventarioCompletoPared getPared() {
        return this.pared;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.pared</code>.
     */
    public VistaInventarioCompleto setPared(VistaInventarioCompletoPared pared) {
        this.pared = pared;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.malla</code>.
     */
    public VistaInventarioCompletoMalla getMalla() {
        return this.malla;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.malla</code>.
     */
    public VistaInventarioCompleto setMalla(VistaInventarioCompletoMalla malla) {
        this.malla = malla;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.horizontal</code>.
     */
    public VistaInventarioCompletoHorizontal getHorizontal() {
        return this.horizontal;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.horizontal</code>.
     */
    public VistaInventarioCompleto setHorizontal(VistaInventarioCompletoHorizontal horizontal) {
        this.horizontal = horizontal;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.estante</code>.
     */
    public VistaInventarioCompletoEstante getEstante() {
        return this.estante;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.estante</code>.
     */
    public VistaInventarioCompleto setEstante(VistaInventarioCompletoEstante estante) {
        this.estante = estante;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.nivel</code>.
     */
    public VistaInventarioCompletoNivel getNivel() {
        return this.nivel;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.nivel</code>.
     */
    public VistaInventarioCompleto setNivel(VistaInventarioCompletoNivel nivel) {
        this.nivel = nivel;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_inventario_completo.piso</code>.
     */
    public VistaInventarioCompletoPiso getPiso() {
        return this.piso;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_inventario_completo.piso</code>.
     */
    public VistaInventarioCompleto setPiso(VistaInventarioCompletoPiso piso) {
        this.piso = piso;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.plastica</code>.
     */
    public VistaInventarioCompletoPlastica getPlastica() {
        return this.plastica;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.plastica</code>.
     */
    public VistaInventarioCompleto setPlastica(VistaInventarioCompletoPlastica plastica) {
        this.plastica = plastica;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.carton</code>.
     */
    public VistaInventarioCompletoCarton getCarton() {
        return this.carton;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.carton</code>.
     */
    public VistaInventarioCompleto setCarton(VistaInventarioCompletoCarton carton) {
        this.carton = carton;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.posicion</code>.
     */
    public String getPosicion() {
        return this.posicion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.posicion</code>.
     */
    public VistaInventarioCompleto setPosicion(String posicion) {
        this.posicion = posicion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.cantidad</code>.
     */
    public UInteger getCantidad() {
        return this.cantidad;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.cantidad</code>.
     */
    public VistaInventarioCompleto setCantidad(UInteger cantidad) {
        this.cantidad = cantidad;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.estado</code>.
     */
    public VistaInventarioCompletoEstado getEstado() {
        return this.estado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.estado</code>.
     */
    public VistaInventarioCompleto setEstado(VistaInventarioCompletoEstado estado) {
        this.estado = estado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.condicion</code>.
     */
    public VistaInventarioCompletoCondicion getCondicion() {
        return this.condicion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.condicion</code>.
     */
    public VistaInventarioCompleto setCondicion(VistaInventarioCompletoCondicion condicion) {
        this.condicion = condicion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.anio_registro</code>.
     */
    public Short getAnioRegistro() {
        return this.anioRegistro;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.anio_registro</code>.
     */
    public VistaInventarioCompleto setAnioRegistro(Short anioRegistro) {
        this.anioRegistro = anioRegistro;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.mes_registro</code>.
     */
    public Byte getMesRegistro() {
        return this.mesRegistro;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.mes_registro</code>.
     */
    public VistaInventarioCompleto setMesRegistro(Byte mesRegistro) {
        this.mesRegistro = mesRegistro;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.fecha_creacion</code>.
     */
    public VistaInventarioCompleto setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.fecha_actualizacion</code>.
     */
    public VistaInventarioCompleto setFechaActualizacion(LocalDateTime fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.activo</code>.
     */
    public Byte getActivo() {
        return this.activo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.activo</code>.
     */
    public VistaInventarioCompleto setActivo(Byte activo) {
        this.activo = activo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return this.codigoVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.codigo_vehiculo</code>.
     */
    public VistaInventarioCompleto setCodigoVehiculo(String codigoVehiculo) {
        this.codigoVehiculo = codigoVehiculo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.marca</code>.
     */
    public String getMarca() {
        return this.marca;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.marca</code>.
     */
    public VistaInventarioCompleto setMarca(String marca) {
        this.marca = marca;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.modelo</code>.
     */
    public String getModelo() {
        return this.modelo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.modelo</code>.
     */
    public VistaInventarioCompleto setModelo(String modelo) {
        this.modelo = modelo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.generacion</code>.
     */
    public String getGeneracion() {
        return this.generacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.generacion</code>.
     */
    public VistaInventarioCompleto setGeneracion(String generacion) {
        this.generacion = generacion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.anio_vehiculo</code>.
     */
    public Integer getAnioVehiculo() {
        return this.anioVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.anio_vehiculo</code>.
     */
    public VistaInventarioCompleto setAnioVehiculo(Integer anioVehiculo) {
        this.anioVehiculo = anioVehiculo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_completo.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return this.claveGeneracion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_completo.clave_generacion</code>.
     */
    public VistaInventarioCompleto setClaveGeneracion(String claveGeneracion) {
        this.claveGeneracion = claveGeneracion;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaInventarioCompleto other = (VistaInventarioCompleto) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.codigoRepuesto == null) {
            if (other.codigoRepuesto != null)
                return false;
        }
        else if (!this.codigoRepuesto.equals(other.codigoRepuesto))
            return false;
        if (this.codigoUbicacion == null) {
            if (other.codigoUbicacion != null)
                return false;
        }
        else if (!this.codigoUbicacion.equals(other.codigoUbicacion))
            return false;
        if (this.imagenUrl == null) {
            if (other.imagenUrl != null)
                return false;
        }
        else if (!this.imagenUrl.equals(other.imagenUrl))
            return false;
        if (this.parteVehiculoId == null) {
            if (other.parteVehiculoId != null)
                return false;
        }
        else if (!this.parteVehiculoId.equals(other.parteVehiculoId))
            return false;
        if (this.parteVehiculo == null) {
            if (other.parteVehiculo != null)
                return false;
        }
        else if (!this.parteVehiculo.equals(other.parteVehiculo))
            return false;
        if (this.descripcion == null) {
            if (other.descripcion != null)
                return false;
        }
        else if (!this.descripcion.equals(other.descripcion))
            return false;
        if (this.precioCosto == null) {
            if (other.precioCosto != null)
                return false;
        }
        else if (!this.precioCosto.equals(other.precioCosto))
            return false;
        if (this.precioVenta == null) {
            if (other.precioVenta != null)
                return false;
        }
        else if (!this.precioVenta.equals(other.precioVenta))
            return false;
        if (this.precioMayoreo == null) {
            if (other.precioMayoreo != null)
                return false;
        }
        else if (!this.precioMayoreo.equals(other.precioMayoreo))
            return false;
        if (this.formula_15 == null) {
            if (other.formula_15 != null)
                return false;
        }
        else if (!this.formula_15.equals(other.formula_15))
            return false;
        if (this.formula_30 == null) {
            if (other.formula_30 != null)
                return false;
        }
        else if (!this.formula_30.equals(other.formula_30))
            return false;
        if (this.bodega == null) {
            if (other.bodega != null)
                return false;
        }
        else if (!this.bodega.equals(other.bodega))
            return false;
        if (this.zona == null) {
            if (other.zona != null)
                return false;
        }
        else if (!this.zona.equals(other.zona))
            return false;
        if (this.pared == null) {
            if (other.pared != null)
                return false;
        }
        else if (!this.pared.equals(other.pared))
            return false;
        if (this.malla == null) {
            if (other.malla != null)
                return false;
        }
        else if (!this.malla.equals(other.malla))
            return false;
        if (this.horizontal == null) {
            if (other.horizontal != null)
                return false;
        }
        else if (!this.horizontal.equals(other.horizontal))
            return false;
        if (this.estante == null) {
            if (other.estante != null)
                return false;
        }
        else if (!this.estante.equals(other.estante))
            return false;
        if (this.nivel == null) {
            if (other.nivel != null)
                return false;
        }
        else if (!this.nivel.equals(other.nivel))
            return false;
        if (this.piso == null) {
            if (other.piso != null)
                return false;
        }
        else if (!this.piso.equals(other.piso))
            return false;
        if (this.plastica == null) {
            if (other.plastica != null)
                return false;
        }
        else if (!this.plastica.equals(other.plastica))
            return false;
        if (this.carton == null) {
            if (other.carton != null)
                return false;
        }
        else if (!this.carton.equals(other.carton))
            return false;
        if (this.posicion == null) {
            if (other.posicion != null)
                return false;
        }
        else if (!this.posicion.equals(other.posicion))
            return false;
        if (this.cantidad == null) {
            if (other.cantidad != null)
                return false;
        }
        else if (!this.cantidad.equals(other.cantidad))
            return false;
        if (this.estado == null) {
            if (other.estado != null)
                return false;
        }
        else if (!this.estado.equals(other.estado))
            return false;
        if (this.condicion == null) {
            if (other.condicion != null)
                return false;
        }
        else if (!this.condicion.equals(other.condicion))
            return false;
        if (this.anioRegistro == null) {
            if (other.anioRegistro != null)
                return false;
        }
        else if (!this.anioRegistro.equals(other.anioRegistro))
            return false;
        if (this.mesRegistro == null) {
            if (other.mesRegistro != null)
                return false;
        }
        else if (!this.mesRegistro.equals(other.mesRegistro))
            return false;
        if (this.fechaCreacion == null) {
            if (other.fechaCreacion != null)
                return false;
        }
        else if (!this.fechaCreacion.equals(other.fechaCreacion))
            return false;
        if (this.fechaActualizacion == null) {
            if (other.fechaActualizacion != null)
                return false;
        }
        else if (!this.fechaActualizacion.equals(other.fechaActualizacion))
            return false;
        if (this.activo == null) {
            if (other.activo != null)
                return false;
        }
        else if (!this.activo.equals(other.activo))
            return false;
        if (this.codigoVehiculo == null) {
            if (other.codigoVehiculo != null)
                return false;
        }
        else if (!this.codigoVehiculo.equals(other.codigoVehiculo))
            return false;
        if (this.marca == null) {
            if (other.marca != null)
                return false;
        }
        else if (!this.marca.equals(other.marca))
            return false;
        if (this.modelo == null) {
            if (other.modelo != null)
                return false;
        }
        else if (!this.modelo.equals(other.modelo))
            return false;
        if (this.generacion == null) {
            if (other.generacion != null)
                return false;
        }
        else if (!this.generacion.equals(other.generacion))
            return false;
        if (this.anioVehiculo == null) {
            if (other.anioVehiculo != null)
                return false;
        }
        else if (!this.anioVehiculo.equals(other.anioVehiculo))
            return false;
        if (this.claveGeneracion == null) {
            if (other.claveGeneracion != null)
                return false;
        }
        else if (!this.claveGeneracion.equals(other.claveGeneracion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.codigoRepuesto == null) ? 0 : this.codigoRepuesto.hashCode());
        result = prime * result + ((this.codigoUbicacion == null) ? 0 : this.codigoUbicacion.hashCode());
        result = prime * result + ((this.imagenUrl == null) ? 0 : this.imagenUrl.hashCode());
        result = prime * result + ((this.parteVehiculoId == null) ? 0 : this.parteVehiculoId.hashCode());
        result = prime * result + ((this.parteVehiculo == null) ? 0 : this.parteVehiculo.hashCode());
        result = prime * result + ((this.descripcion == null) ? 0 : this.descripcion.hashCode());
        result = prime * result + ((this.precioCosto == null) ? 0 : this.precioCosto.hashCode());
        result = prime * result + ((this.precioVenta == null) ? 0 : this.precioVenta.hashCode());
        result = prime * result + ((this.precioMayoreo == null) ? 0 : this.precioMayoreo.hashCode());
        result = prime * result + ((this.formula_15 == null) ? 0 : this.formula_15.hashCode());
        result = prime * result + ((this.formula_30 == null) ? 0 : this.formula_30.hashCode());
        result = prime * result + ((this.bodega == null) ? 0 : this.bodega.hashCode());
        result = prime * result + ((this.zona == null) ? 0 : this.zona.hashCode());
        result = prime * result + ((this.pared == null) ? 0 : this.pared.hashCode());
        result = prime * result + ((this.malla == null) ? 0 : this.malla.hashCode());
        result = prime * result + ((this.horizontal == null) ? 0 : this.horizontal.hashCode());
        result = prime * result + ((this.estante == null) ? 0 : this.estante.hashCode());
        result = prime * result + ((this.nivel == null) ? 0 : this.nivel.hashCode());
        result = prime * result + ((this.piso == null) ? 0 : this.piso.hashCode());
        result = prime * result + ((this.plastica == null) ? 0 : this.plastica.hashCode());
        result = prime * result + ((this.carton == null) ? 0 : this.carton.hashCode());
        result = prime * result + ((this.posicion == null) ? 0 : this.posicion.hashCode());
        result = prime * result + ((this.cantidad == null) ? 0 : this.cantidad.hashCode());
        result = prime * result + ((this.estado == null) ? 0 : this.estado.hashCode());
        result = prime * result + ((this.condicion == null) ? 0 : this.condicion.hashCode());
        result = prime * result + ((this.anioRegistro == null) ? 0 : this.anioRegistro.hashCode());
        result = prime * result + ((this.mesRegistro == null) ? 0 : this.mesRegistro.hashCode());
        result = prime * result + ((this.fechaCreacion == null) ? 0 : this.fechaCreacion.hashCode());
        result = prime * result + ((this.fechaActualizacion == null) ? 0 : this.fechaActualizacion.hashCode());
        result = prime * result + ((this.activo == null) ? 0 : this.activo.hashCode());
        result = prime * result + ((this.codigoVehiculo == null) ? 0 : this.codigoVehiculo.hashCode());
        result = prime * result + ((this.marca == null) ? 0 : this.marca.hashCode());
        result = prime * result + ((this.modelo == null) ? 0 : this.modelo.hashCode());
        result = prime * result + ((this.generacion == null) ? 0 : this.generacion.hashCode());
        result = prime * result + ((this.anioVehiculo == null) ? 0 : this.anioVehiculo.hashCode());
        result = prime * result + ((this.claveGeneracion == null) ? 0 : this.claveGeneracion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaInventarioCompleto (");

        sb.append(id);
        sb.append(", ").append(codigoRepuesto);
        sb.append(", ").append(codigoUbicacion);
        sb.append(", ").append(imagenUrl);
        sb.append(", ").append(parteVehiculoId);
        sb.append(", ").append(parteVehiculo);
        sb.append(", ").append(descripcion);
        sb.append(", ").append(precioCosto);
        sb.append(", ").append(precioVenta);
        sb.append(", ").append(precioMayoreo);
        sb.append(", ").append(formula_15);
        sb.append(", ").append(formula_30);
        sb.append(", ").append(bodega);
        sb.append(", ").append(zona);
        sb.append(", ").append(pared);
        sb.append(", ").append(malla);
        sb.append(", ").append(horizontal);
        sb.append(", ").append(estante);
        sb.append(", ").append(nivel);
        sb.append(", ").append(piso);
        sb.append(", ").append(plastica);
        sb.append(", ").append(carton);
        sb.append(", ").append(posicion);
        sb.append(", ").append(cantidad);
        sb.append(", ").append(estado);
        sb.append(", ").append(condicion);
        sb.append(", ").append(anioRegistro);
        sb.append(", ").append(mesRegistro);
        sb.append(", ").append(fechaCreacion);
        sb.append(", ").append(fechaActualizacion);
        sb.append(", ").append(activo);
        sb.append(", ").append(codigoVehiculo);
        sb.append(", ").append(marca);
        sb.append(", ").append(modelo);
        sb.append(", ").append(generacion);
        sb.append(", ").append(anioVehiculo);
        sb.append(", ").append(claveGeneracion);

        sb.append(")");
        return sb.toString();
    }
}
