/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.pojos;


import com.rodiejacontable.database.jooq.enums.VistaResumenPagosComisionesEstado;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VistaResumenPagosComisiones implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer anio;
    private Integer mes;
    private String nombreEmpleado;
    private BigDecimal totalComisiones;
    private LocalDate fechaPago;
    private VistaResumenPagosComisionesEstado estado;
    private String referenciaPago;
    private String notas;
    private LocalDateTime fechaRegistro;
    private Long cantidadTransaccionesPagadas;
    private BigDecimal porcentajeComisionReal;

    public VistaResumenPagosComisiones() {}

    public VistaResumenPagosComisiones(VistaResumenPagosComisiones value) {
        this.id = value.id;
        this.anio = value.anio;
        this.mes = value.mes;
        this.nombreEmpleado = value.nombreEmpleado;
        this.totalComisiones = value.totalComisiones;
        this.fechaPago = value.fechaPago;
        this.estado = value.estado;
        this.referenciaPago = value.referenciaPago;
        this.notas = value.notas;
        this.fechaRegistro = value.fechaRegistro;
        this.cantidadTransaccionesPagadas = value.cantidadTransaccionesPagadas;
        this.porcentajeComisionReal = value.porcentajeComisionReal;
    }

    public VistaResumenPagosComisiones(
        Integer id,
        Integer anio,
        Integer mes,
        String nombreEmpleado,
        BigDecimal totalComisiones,
        LocalDate fechaPago,
        VistaResumenPagosComisionesEstado estado,
        String referenciaPago,
        String notas,
        LocalDateTime fechaRegistro,
        Long cantidadTransaccionesPagadas,
        BigDecimal porcentajeComisionReal
    ) {
        this.id = id;
        this.anio = anio;
        this.mes = mes;
        this.nombreEmpleado = nombreEmpleado;
        this.totalComisiones = totalComisiones;
        this.fechaPago = fechaPago;
        this.estado = estado;
        this.referenciaPago = referenciaPago;
        this.notas = notas;
        this.fechaRegistro = fechaRegistro;
        this.cantidadTransaccionesPagadas = cantidadTransaccionesPagadas;
        this.porcentajeComisionReal = porcentajeComisionReal;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.id</code>.
     */
    public VistaResumenPagosComisiones setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.anio</code>.
     */
    public Integer getAnio() {
        return this.anio;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.anio</code>.
     */
    public VistaResumenPagosComisiones setAnio(Integer anio) {
        this.anio = anio;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.mes</code>.
     */
    public Integer getMes() {
        return this.mes;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.mes</code>.
     */
    public VistaResumenPagosComisiones setMes(Integer mes) {
        this.mes = mes;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.nombre_empleado</code>.
     */
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.nombre_empleado</code>.
     */
    public VistaResumenPagosComisiones setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.total_comisiones</code>.
     */
    public BigDecimal getTotalComisiones() {
        return this.totalComisiones;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.total_comisiones</code>.
     */
    public VistaResumenPagosComisiones setTotalComisiones(BigDecimal totalComisiones) {
        this.totalComisiones = totalComisiones;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.fecha_pago</code>.
     */
    public LocalDate getFechaPago() {
        return this.fechaPago;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.fecha_pago</code>.
     */
    public VistaResumenPagosComisiones setFechaPago(LocalDate fechaPago) {
        this.fechaPago = fechaPago;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.estado</code>.
     */
    public VistaResumenPagosComisionesEstado getEstado() {
        return this.estado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.estado</code>.
     */
    public VistaResumenPagosComisiones setEstado(VistaResumenPagosComisionesEstado estado) {
        this.estado = estado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.referencia_pago</code>.
     */
    public String getReferenciaPago() {
        return this.referenciaPago;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.referencia_pago</code>.
     */
    public VistaResumenPagosComisiones setReferenciaPago(String referenciaPago) {
        this.referenciaPago = referenciaPago;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.notas</code>.
     */
    public String getNotas() {
        return this.notas;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.notas</code>.
     */
    public VistaResumenPagosComisiones setNotas(String notas) {
        this.notas = notas;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.fecha_registro</code>.
     */
    public LocalDateTime getFechaRegistro() {
        return this.fechaRegistro;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.fecha_registro</code>.
     */
    public VistaResumenPagosComisiones setFechaRegistro(LocalDateTime fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.cantidad_transacciones_pagadas</code>.
     */
    public Long getCantidadTransaccionesPagadas() {
        return this.cantidadTransaccionesPagadas;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.cantidad_transacciones_pagadas</code>.
     */
    public VistaResumenPagosComisiones setCantidadTransaccionesPagadas(Long cantidadTransaccionesPagadas) {
        this.cantidadTransaccionesPagadas = cantidadTransaccionesPagadas;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.porcentaje_comision_real</code>.
     */
    public BigDecimal getPorcentajeComisionReal() {
        return this.porcentajeComisionReal;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_pagos_comisiones.porcentaje_comision_real</code>.
     */
    public VistaResumenPagosComisiones setPorcentajeComisionReal(BigDecimal porcentajeComisionReal) {
        this.porcentajeComisionReal = porcentajeComisionReal;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaResumenPagosComisiones other = (VistaResumenPagosComisiones) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.anio == null) {
            if (other.anio != null)
                return false;
        }
        else if (!this.anio.equals(other.anio))
            return false;
        if (this.mes == null) {
            if (other.mes != null)
                return false;
        }
        else if (!this.mes.equals(other.mes))
            return false;
        if (this.nombreEmpleado == null) {
            if (other.nombreEmpleado != null)
                return false;
        }
        else if (!this.nombreEmpleado.equals(other.nombreEmpleado))
            return false;
        if (this.totalComisiones == null) {
            if (other.totalComisiones != null)
                return false;
        }
        else if (!this.totalComisiones.equals(other.totalComisiones))
            return false;
        if (this.fechaPago == null) {
            if (other.fechaPago != null)
                return false;
        }
        else if (!this.fechaPago.equals(other.fechaPago))
            return false;
        if (this.estado == null) {
            if (other.estado != null)
                return false;
        }
        else if (!this.estado.equals(other.estado))
            return false;
        if (this.referenciaPago == null) {
            if (other.referenciaPago != null)
                return false;
        }
        else if (!this.referenciaPago.equals(other.referenciaPago))
            return false;
        if (this.notas == null) {
            if (other.notas != null)
                return false;
        }
        else if (!this.notas.equals(other.notas))
            return false;
        if (this.fechaRegistro == null) {
            if (other.fechaRegistro != null)
                return false;
        }
        else if (!this.fechaRegistro.equals(other.fechaRegistro))
            return false;
        if (this.cantidadTransaccionesPagadas == null) {
            if (other.cantidadTransaccionesPagadas != null)
                return false;
        }
        else if (!this.cantidadTransaccionesPagadas.equals(other.cantidadTransaccionesPagadas))
            return false;
        if (this.porcentajeComisionReal == null) {
            if (other.porcentajeComisionReal != null)
                return false;
        }
        else if (!this.porcentajeComisionReal.equals(other.porcentajeComisionReal))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.anio == null) ? 0 : this.anio.hashCode());
        result = prime * result + ((this.mes == null) ? 0 : this.mes.hashCode());
        result = prime * result + ((this.nombreEmpleado == null) ? 0 : this.nombreEmpleado.hashCode());
        result = prime * result + ((this.totalComisiones == null) ? 0 : this.totalComisiones.hashCode());
        result = prime * result + ((this.fechaPago == null) ? 0 : this.fechaPago.hashCode());
        result = prime * result + ((this.estado == null) ? 0 : this.estado.hashCode());
        result = prime * result + ((this.referenciaPago == null) ? 0 : this.referenciaPago.hashCode());
        result = prime * result + ((this.notas == null) ? 0 : this.notas.hashCode());
        result = prime * result + ((this.fechaRegistro == null) ? 0 : this.fechaRegistro.hashCode());
        result = prime * result + ((this.cantidadTransaccionesPagadas == null) ? 0 : this.cantidadTransaccionesPagadas.hashCode());
        result = prime * result + ((this.porcentajeComisionReal == null) ? 0 : this.porcentajeComisionReal.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaResumenPagosComisiones (");

        sb.append(id);
        sb.append(", ").append(anio);
        sb.append(", ").append(mes);
        sb.append(", ").append(nombreEmpleado);
        sb.append(", ").append(totalComisiones);
        sb.append(", ").append(fechaPago);
        sb.append(", ").append(estado);
        sb.append(", ").append(referenciaPago);
        sb.append(", ").append(notas);
        sb.append(", ").append(fechaRegistro);
        sb.append(", ").append(cantidadTransaccionesPagadas);
        sb.append(", ").append(porcentajeComisionReal);

        sb.append(")");
        return sb.toString();
    }
}
