/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq;


import com.rodiejacontable.database.jooq.tables.Empleados;
import com.rodiejacontable.database.jooq.tables.Generaciones;
import com.rodiejacontable.database.jooq.tables.HistorialRepuestos;
import com.rodiejacontable.database.jooq.tables.HistorialTransacciones;
import com.rodiejacontable.database.jooq.tables.HistorialVehiculos;
import com.rodiejacontable.database.jooq.tables.InventarioRepuestos;
import com.rodiejacontable.database.jooq.tables.Marcas;
import com.rodiejacontable.database.jooq.tables.Modelos;
import com.rodiejacontable.database.jooq.tables.PagosComisiones;
import com.rodiejacontable.database.jooq.tables.TiposTransacciones;
import com.rodiejacontable.database.jooq.tables.TransaccionesFinancieras;
import com.rodiejacontable.database.jooq.tables.Vehiculos;
import com.rodiejacontable.database.jooq.tables.records.EmpleadosRecord;
import com.rodiejacontable.database.jooq.tables.records.GeneracionesRecord;
import com.rodiejacontable.database.jooq.tables.records.HistorialRepuestosRecord;
import com.rodiejacontable.database.jooq.tables.records.HistorialTransaccionesRecord;
import com.rodiejacontable.database.jooq.tables.records.HistorialVehiculosRecord;
import com.rodiejacontable.database.jooq.tables.records.InventarioRepuestosRecord;
import com.rodiejacontable.database.jooq.tables.records.MarcasRecord;
import com.rodiejacontable.database.jooq.tables.records.ModelosRecord;
import com.rodiejacontable.database.jooq.tables.records.PagosComisionesRecord;
import com.rodiejacontable.database.jooq.tables.records.TiposTransaccionesRecord;
import com.rodiejacontable.database.jooq.tables.records.TransaccionesFinancierasRecord;
import com.rodiejacontable.database.jooq.tables.records.VehiculosRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * sistema_vehicular.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmpleadosRecord> KEY_EMPLEADOS_NOMBRE = Internal.createUniqueKey(Empleados.EMPLEADOS, DSL.name("KEY_empleados_nombre"), new TableField[] { Empleados.EMPLEADOS.NOMBRE }, true);
    public static final UniqueKey<EmpleadosRecord> KEY_EMPLEADOS_PRIMARY = Internal.createUniqueKey(Empleados.EMPLEADOS, DSL.name("KEY_empleados_PRIMARY"), new TableField[] { Empleados.EMPLEADOS.ID }, true);
    public static final UniqueKey<GeneracionesRecord> KEY_GENERACIONES_PRIMARY = Internal.createUniqueKey(Generaciones.GENERACIONES, DSL.name("KEY_generaciones_PRIMARY"), new TableField[] { Generaciones.GENERACIONES.ID }, true);
    public static final UniqueKey<GeneracionesRecord> KEY_GENERACIONES_UNIQUE_MODELO_GENERACION = Internal.createUniqueKey(Generaciones.GENERACIONES, DSL.name("KEY_generaciones_unique_modelo_generacion"), new TableField[] { Generaciones.GENERACIONES.MODELO_ID, Generaciones.GENERACIONES.NOMBRE }, true);
    public static final UniqueKey<HistorialRepuestosRecord> KEY_HISTORIAL_REPUESTOS_PRIMARY = Internal.createUniqueKey(HistorialRepuestos.HISTORIAL_REPUESTOS, DSL.name("KEY_historial_repuestos_PRIMARY"), new TableField[] { HistorialRepuestos.HISTORIAL_REPUESTOS.ID }, true);
    public static final UniqueKey<HistorialTransaccionesRecord> KEY_HISTORIAL_TRANSACCIONES_PRIMARY = Internal.createUniqueKey(HistorialTransacciones.HISTORIAL_TRANSACCIONES, DSL.name("KEY_historial_transacciones_PRIMARY"), new TableField[] { HistorialTransacciones.HISTORIAL_TRANSACCIONES.ID }, true);
    public static final UniqueKey<HistorialVehiculosRecord> KEY_HISTORIAL_VEHICULOS_PRIMARY = Internal.createUniqueKey(HistorialVehiculos.HISTORIAL_VEHICULOS, DSL.name("KEY_historial_vehiculos_PRIMARY"), new TableField[] { HistorialVehiculos.HISTORIAL_VEHICULOS.ID }, true);
    public static final UniqueKey<InventarioRepuestosRecord> KEY_INVENTARIO_REPUESTOS_CODIGO_REPUESTO = Internal.createUniqueKey(InventarioRepuestos.INVENTARIO_REPUESTOS, DSL.name("KEY_inventario_repuestos_codigo_repuesto"), new TableField[] { InventarioRepuestos.INVENTARIO_REPUESTOS.CODIGO_REPUESTO }, true);
    public static final UniqueKey<InventarioRepuestosRecord> KEY_INVENTARIO_REPUESTOS_PRIMARY = Internal.createUniqueKey(InventarioRepuestos.INVENTARIO_REPUESTOS, DSL.name("KEY_inventario_repuestos_PRIMARY"), new TableField[] { InventarioRepuestos.INVENTARIO_REPUESTOS.ID }, true);
    public static final UniqueKey<MarcasRecord> KEY_MARCAS_NOMBRE = Internal.createUniqueKey(Marcas.MARCAS, DSL.name("KEY_marcas_nombre"), new TableField[] { Marcas.MARCAS.NOMBRE }, true);
    public static final UniqueKey<MarcasRecord> KEY_MARCAS_PRIMARY = Internal.createUniqueKey(Marcas.MARCAS, DSL.name("KEY_marcas_PRIMARY"), new TableField[] { Marcas.MARCAS.ID }, true);
    public static final UniqueKey<ModelosRecord> KEY_MODELOS_PRIMARY = Internal.createUniqueKey(Modelos.MODELOS, DSL.name("KEY_modelos_PRIMARY"), new TableField[] { Modelos.MODELOS.ID }, true);
    public static final UniqueKey<ModelosRecord> KEY_MODELOS_UNIQUE_MARCA_MODELO = Internal.createUniqueKey(Modelos.MODELOS, DSL.name("KEY_modelos_unique_marca_modelo"), new TableField[] { Modelos.MODELOS.MARCA_ID, Modelos.MODELOS.NOMBRE }, true);
    public static final UniqueKey<PagosComisionesRecord> KEY_PAGOS_COMISIONES_PRIMARY = Internal.createUniqueKey(PagosComisiones.PAGOS_COMISIONES, DSL.name("KEY_pagos_comisiones_PRIMARY"), new TableField[] { PagosComisiones.PAGOS_COMISIONES.ID }, true);
    public static final UniqueKey<PagosComisionesRecord> KEY_PAGOS_COMISIONES_UNIQUE_PAGO_PERIODO = Internal.createUniqueKey(PagosComisiones.PAGOS_COMISIONES, DSL.name("KEY_pagos_comisiones_unique_pago_periodo"), new TableField[] { PagosComisiones.PAGOS_COMISIONES.EMPLEADO_ID, PagosComisiones.PAGOS_COMISIONES.ANIO, PagosComisiones.PAGOS_COMISIONES.MES }, true);
    public static final UniqueKey<TiposTransaccionesRecord> KEY_TIPOS_TRANSACCIONES_NOMBRE = Internal.createUniqueKey(TiposTransacciones.TIPOS_TRANSACCIONES, DSL.name("KEY_tipos_transacciones_nombre"), new TableField[] { TiposTransacciones.TIPOS_TRANSACCIONES.NOMBRE }, true);
    public static final UniqueKey<TiposTransaccionesRecord> KEY_TIPOS_TRANSACCIONES_PRIMARY = Internal.createUniqueKey(TiposTransacciones.TIPOS_TRANSACCIONES, DSL.name("KEY_tipos_transacciones_PRIMARY"), new TableField[] { TiposTransacciones.TIPOS_TRANSACCIONES.ID }, true);
    public static final UniqueKey<TransaccionesFinancierasRecord> KEY_TRANSACCIONES_FINANCIERAS_CODIGO_TRANSACCION = Internal.createUniqueKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("KEY_transacciones_financieras_codigo_transaccion"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.CODIGO_TRANSACCION }, true);
    public static final UniqueKey<TransaccionesFinancierasRecord> KEY_TRANSACCIONES_FINANCIERAS_PRIMARY = Internal.createUniqueKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("KEY_transacciones_financieras_PRIMARY"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.ID }, true);
    public static final UniqueKey<VehiculosRecord> KEY_VEHICULOS_CODIGO_VEHICULO = Internal.createUniqueKey(Vehiculos.VEHICULOS, DSL.name("KEY_vehiculos_codigo_vehiculo"), new TableField[] { Vehiculos.VEHICULOS.CODIGO_VEHICULO }, true);
    public static final UniqueKey<VehiculosRecord> KEY_VEHICULOS_PRIMARY = Internal.createUniqueKey(Vehiculos.VEHICULOS, DSL.name("KEY_vehiculos_PRIMARY"), new TableField[] { Vehiculos.VEHICULOS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GeneracionesRecord, ModelosRecord> GENERACIONES_IBFK_1 = Internal.createForeignKey(Generaciones.GENERACIONES, DSL.name("generaciones_ibfk_1"), new TableField[] { Generaciones.GENERACIONES.MODELO_ID }, Keys.KEY_MODELOS_PRIMARY, new TableField[] { Modelos.MODELOS.ID }, true);
    public static final ForeignKey<HistorialRepuestosRecord, InventarioRepuestosRecord> HISTORIAL_REPUESTOS_IBFK_1 = Internal.createForeignKey(HistorialRepuestos.HISTORIAL_REPUESTOS, DSL.name("historial_repuestos_ibfk_1"), new TableField[] { HistorialRepuestos.HISTORIAL_REPUESTOS.REPUESTO_ID }, Keys.KEY_INVENTARIO_REPUESTOS_PRIMARY, new TableField[] { InventarioRepuestos.INVENTARIO_REPUESTOS.ID }, true);
    public static final ForeignKey<HistorialTransaccionesRecord, TransaccionesFinancierasRecord> HISTORIAL_TRANSACCIONES_IBFK_1 = Internal.createForeignKey(HistorialTransacciones.HISTORIAL_TRANSACCIONES, DSL.name("historial_transacciones_ibfk_1"), new TableField[] { HistorialTransacciones.HISTORIAL_TRANSACCIONES.TRANSACCION_ID }, Keys.KEY_TRANSACCIONES_FINANCIERAS_PRIMARY, new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.ID }, true);
    public static final ForeignKey<HistorialVehiculosRecord, VehiculosRecord> HISTORIAL_VEHICULOS_IBFK_1 = Internal.createForeignKey(HistorialVehiculos.HISTORIAL_VEHICULOS, DSL.name("historial_vehiculos_ibfk_1"), new TableField[] { HistorialVehiculos.HISTORIAL_VEHICULOS.VEHICULO_ID }, Keys.KEY_VEHICULOS_PRIMARY, new TableField[] { Vehiculos.VEHICULOS.ID }, true);
    public static final ForeignKey<InventarioRepuestosRecord, VehiculosRecord> INVENTARIO_REPUESTOS_IBFK_1 = Internal.createForeignKey(InventarioRepuestos.INVENTARIO_REPUESTOS, DSL.name("inventario_repuestos_ibfk_1"), new TableField[] { InventarioRepuestos.INVENTARIO_REPUESTOS.VEHICULO_ORIGEN_ID }, Keys.KEY_VEHICULOS_PRIMARY, new TableField[] { Vehiculos.VEHICULOS.ID }, true);
    public static final ForeignKey<ModelosRecord, MarcasRecord> MODELOS_IBFK_1 = Internal.createForeignKey(Modelos.MODELOS, DSL.name("modelos_ibfk_1"), new TableField[] { Modelos.MODELOS.MARCA_ID }, Keys.KEY_MARCAS_PRIMARY, new TableField[] { Marcas.MARCAS.ID }, true);
    public static final ForeignKey<PagosComisionesRecord, EmpleadosRecord> PAGOS_COMISIONES_IBFK_1 = Internal.createForeignKey(PagosComisiones.PAGOS_COMISIONES, DSL.name("pagos_comisiones_ibfk_1"), new TableField[] { PagosComisiones.PAGOS_COMISIONES.EMPLEADO_ID }, Keys.KEY_EMPLEADOS_PRIMARY, new TableField[] { Empleados.EMPLEADOS.ID }, true);
    public static final ForeignKey<TransaccionesFinancierasRecord, TiposTransaccionesRecord> TRANSACCIONES_FINANCIERAS_IBFK_1 = Internal.createForeignKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("transacciones_financieras_ibfk_1"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.TIPO_TRANSACCION_ID }, Keys.KEY_TIPOS_TRANSACCIONES_PRIMARY, new TableField[] { TiposTransacciones.TIPOS_TRANSACCIONES.ID }, true);
    public static final ForeignKey<TransaccionesFinancierasRecord, EmpleadosRecord> TRANSACCIONES_FINANCIERAS_IBFK_2 = Internal.createForeignKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("transacciones_financieras_ibfk_2"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.EMPLEADO_ID }, Keys.KEY_EMPLEADOS_PRIMARY, new TableField[] { Empleados.EMPLEADOS.ID }, true);
    public static final ForeignKey<TransaccionesFinancierasRecord, VehiculosRecord> TRANSACCIONES_FINANCIERAS_IBFK_3 = Internal.createForeignKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("transacciones_financieras_ibfk_3"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.VEHICULO_ID }, Keys.KEY_VEHICULOS_PRIMARY, new TableField[] { Vehiculos.VEHICULOS.ID }, true);
    public static final ForeignKey<TransaccionesFinancierasRecord, InventarioRepuestosRecord> TRANSACCIONES_FINANCIERAS_IBFK_4 = Internal.createForeignKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("transacciones_financieras_ibfk_4"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.REPUESTO_ID }, Keys.KEY_INVENTARIO_REPUESTOS_PRIMARY, new TableField[] { InventarioRepuestos.INVENTARIO_REPUESTOS.ID }, true);
    public static final ForeignKey<TransaccionesFinancierasRecord, GeneracionesRecord> TRANSACCIONES_FINANCIERAS_IBFK_5 = Internal.createForeignKey(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS, DSL.name("transacciones_financieras_ibfk_5"), new TableField[] { TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS.GENERACION_ID }, Keys.KEY_GENERACIONES_PRIMARY, new TableField[] { Generaciones.GENERACIONES.ID }, true);
    public static final ForeignKey<VehiculosRecord, GeneracionesRecord> VEHICULOS_IBFK_1 = Internal.createForeignKey(Vehiculos.VEHICULOS, DSL.name("vehiculos_ibfk_1"), new TableField[] { Vehiculos.VEHICULOS.GENERACION_ID }, Keys.KEY_GENERACIONES_PRIMARY, new TableField[] { Generaciones.GENERACIONES.ID }, true);
}
