/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq;


import com.rodiejacontable.database.jooq.tables.Empleados;
import com.rodiejacontable.database.jooq.tables.Generaciones;
import com.rodiejacontable.database.jooq.tables.HistorialRepuestos;
import com.rodiejacontable.database.jooq.tables.HistorialTransacciones;
import com.rodiejacontable.database.jooq.tables.HistorialVehiculos;
import com.rodiejacontable.database.jooq.tables.InventarioRepuestos;
import com.rodiejacontable.database.jooq.tables.Marcas;
import com.rodiejacontable.database.jooq.tables.Modelos;
import com.rodiejacontable.database.jooq.tables.PagosComisiones;
import com.rodiejacontable.database.jooq.tables.TiposTransacciones;
import com.rodiejacontable.database.jooq.tables.TransaccionesFinancieras;
import com.rodiejacontable.database.jooq.tables.Vehiculos;
import com.rodiejacontable.database.jooq.tables.VistaAnalisisFinancieroMensual;
import com.rodiejacontable.database.jooq.tables.VistaAuditoriaCompleta;
import com.rodiejacontable.database.jooq.tables.VistaDashboardEjecutivo;
import com.rodiejacontable.database.jooq.tables.VistaExcelVentasMesCompleta;
import com.rodiejacontable.database.jooq.tables.VistaInventarioCompleto;
import com.rodiejacontable.database.jooq.tables.VistaInventarioCritico;
import com.rodiejacontable.database.jooq.tables.VistaRentabilidadGeneraciones;
import com.rodiejacontable.database.jooq.tables.VistaResumenGeneraciones;
import com.rodiejacontable.database.jooq.tables.VistaResumenPagosComisiones;
import com.rodiejacontable.database.jooq.tables.VistaTopProductosVendidos;
import com.rodiejacontable.database.jooq.tables.VistaTransaccionesCompletas;
import com.rodiejacontable.database.jooq.tables.VistaVehiculosCompleta;
import com.rodiejacontable.database.jooq.tables.VistaVentasEmpleadoMensual;
import com.rodiejacontable.database.jooq.tables.VistaVentasPorEmpleado;


/**
 * Convenience access to all tables in sistema_vehicular.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sistema_vehicular.empleados</code>.
     */
    public static final Empleados EMPLEADOS = Empleados.EMPLEADOS;

    /**
     * The table <code>sistema_vehicular.generaciones</code>.
     */
    public static final Generaciones GENERACIONES = Generaciones.GENERACIONES;

    /**
     * The table <code>sistema_vehicular.historial_repuestos</code>.
     */
    public static final HistorialRepuestos HISTORIAL_REPUESTOS = HistorialRepuestos.HISTORIAL_REPUESTOS;

    /**
     * The table <code>sistema_vehicular.historial_transacciones</code>.
     */
    public static final HistorialTransacciones HISTORIAL_TRANSACCIONES = HistorialTransacciones.HISTORIAL_TRANSACCIONES;

    /**
     * The table <code>sistema_vehicular.historial_vehiculos</code>.
     */
    public static final HistorialVehiculos HISTORIAL_VEHICULOS = HistorialVehiculos.HISTORIAL_VEHICULOS;

    /**
     * The table <code>sistema_vehicular.inventario_repuestos</code>.
     */
    public static final InventarioRepuestos INVENTARIO_REPUESTOS = InventarioRepuestos.INVENTARIO_REPUESTOS;

    /**
     * The table <code>sistema_vehicular.marcas</code>.
     */
    public static final Marcas MARCAS = Marcas.MARCAS;

    /**
     * The table <code>sistema_vehicular.modelos</code>.
     */
    public static final Modelos MODELOS = Modelos.MODELOS;

    /**
     * The table <code>sistema_vehicular.pagos_comisiones</code>.
     */
    public static final PagosComisiones PAGOS_COMISIONES = PagosComisiones.PAGOS_COMISIONES;

    /**
     * The table <code>sistema_vehicular.tipos_transacciones</code>.
     */
    public static final TiposTransacciones TIPOS_TRANSACCIONES = TiposTransacciones.TIPOS_TRANSACCIONES;

    /**
     * The table <code>sistema_vehicular.transacciones_financieras</code>.
     */
    public static final TransaccionesFinancieras TRANSACCIONES_FINANCIERAS = TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS;

    /**
     * The table <code>sistema_vehicular.vehiculos</code>.
     */
    public static final Vehiculos VEHICULOS = Vehiculos.VEHICULOS;

    /**
     * VIEW
     */
    public static final VistaAnalisisFinancieroMensual VISTA_ANALISIS_FINANCIERO_MENSUAL = VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL;

    /**
     * VIEW
     */
    public static final VistaAuditoriaCompleta VISTA_AUDITORIA_COMPLETA = VistaAuditoriaCompleta.VISTA_AUDITORIA_COMPLETA;

    /**
     * VIEW
     */
    public static final VistaDashboardEjecutivo VISTA_DASHBOARD_EJECUTIVO = VistaDashboardEjecutivo.VISTA_DASHBOARD_EJECUTIVO;

    /**
     * VIEW
     */
    public static final VistaExcelVentasMesCompleta VISTA_EXCEL_VENTAS_MES_COMPLETA = VistaExcelVentasMesCompleta.VISTA_EXCEL_VENTAS_MES_COMPLETA;

    /**
     * VIEW
     */
    public static final VistaInventarioCompleto VISTA_INVENTARIO_COMPLETO = VistaInventarioCompleto.VISTA_INVENTARIO_COMPLETO;

    /**
     * VIEW
     */
    public static final VistaInventarioCritico VISTA_INVENTARIO_CRITICO = VistaInventarioCritico.VISTA_INVENTARIO_CRITICO;

    /**
     * VIEW
     */
    public static final VistaRentabilidadGeneraciones VISTA_RENTABILIDAD_GENERACIONES = VistaRentabilidadGeneraciones.VISTA_RENTABILIDAD_GENERACIONES;

    /**
     * VIEW
     */
    public static final VistaResumenGeneraciones VISTA_RESUMEN_GENERACIONES = VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES;

    /**
     * VIEW
     */
    public static final VistaResumenPagosComisiones VISTA_RESUMEN_PAGOS_COMISIONES = VistaResumenPagosComisiones.VISTA_RESUMEN_PAGOS_COMISIONES;

    /**
     * VIEW
     */
    public static final VistaTopProductosVendidos VISTA_TOP_PRODUCTOS_VENDIDOS = VistaTopProductosVendidos.VISTA_TOP_PRODUCTOS_VENDIDOS;

    /**
     * VIEW
     */
    public static final VistaTransaccionesCompletas VISTA_TRANSACCIONES_COMPLETAS = VistaTransaccionesCompletas.VISTA_TRANSACCIONES_COMPLETAS;

    /**
     * VIEW
     */
    public static final VistaVehiculosCompleta VISTA_VEHICULOS_COMPLETA = VistaVehiculosCompleta.VISTA_VEHICULOS_COMPLETA;

    /**
     * VIEW
     */
    public static final VistaVentasEmpleadoMensual VISTA_VENTAS_EMPLEADO_MENSUAL = VistaVentasEmpleadoMensual.VISTA_VENTAS_EMPLEADO_MENSUAL;

    /**
     * VIEW
     */
    public static final VistaVentasPorEmpleado VISTA_VENTAS_POR_EMPLEADO = VistaVentasPorEmpleado.VISTA_VENTAS_POR_EMPLEADO;
}
